
[[_fuse_install_feature]]
===== Installing the Keycloak Feature

You must first install the `keycloak` feature in the JBoss Fuse environment. The keycloak feature includes the Fuse adapter and all third-party dependencies. You can install it either from the Maven repository or from an archive.

====== Installing from the Maven Repository

As a prerequisite, you must be online and have access to the Maven repository.

ifeval::[{project_community}==true]
For community it's sufficient to be online as all the artifacts and 3rd party dependencies should be available in the maven central repository.
endif::[]
ifeval::[{project_product}==true]
For {project_name} you first need to configure a proper Maven repository, so you can install the artifacts. For more information see the
https://access.redhat.com/maven-repository[JBoss Enterprise Maven repository] page.

Assuming the Maven repository is {maven_repository}, add the following to the `$FUSE_HOME/etc/org.ops4j.pax.url.mvn.cfg` file and add the repository to the list of supported repositories. For example:

[source,subs="attributes"]
----
 org.ops4j.pax.url.mvn.repositories= \
    {maven_repository}@id=redhat.product.repo
    http://repo1.maven.org/maven2@id=maven.central.repo, \
    ...
----
endif::[]

To install the keycloak feature using the Maven repository, complete the following steps:

. Start {fuseVersion}; then in the Karaf terminal type:
+
[source,subs="attributes"]
----
features:addurl mvn:org.keycloak/keycloak-osgi-features/{project_versionMvn}/xml/features
features:install keycloak
----

. You might also need to install the Jetty 9 feature:
+
[source]
----
features:install keycloak-jetty9-adapter
----
+
NOTE: If you are using JBoss Fuse 6.2 or later, use `keycloak-jetty8-adapter`. However, upgrading to {fuseVersion} is recommended.

. Ensure that the features were installed:

[source]
----
features:list | grep keycloak
----

====== Installing from the ZIP bundle

This is useful if you are offline or do not want to use Maven to obtain the JAR files and other artifacts.

To install the Fuse adapter from the ZIP archive, complete the following steps:

. Download the {project_name} Fuse adapter ZIP archive.
. Unzip it into the root directory of JBoss Fuse. The dependencies are then installed under the `system` directory. You can overwrite all existing jar files.
+
Use this for {fuseVersion}:
+
[source,subs="attributes"]
----
cd /path-to-fuse/jboss-fuse-6.3.0.redhat-254
ifeval::[{project_community}==true]
unzip -q /path-to-adapter-zip/keycloak-fuse-adapter-{project_versionMvn}.zip
endif::[]
ifeval::[{project_product}==true]
unzip -q /path-to-adapter-zip/rh-sso-{project_version}-fuse-adapter.zip
endif::[]
----
. Start Fuse and run these commands in the fuse/karaf terminal:
+
[source,subs="attributes"]
----
features:addurl mvn:org.keycloak/keycloak-osgi-features/{project_versionMvn}/xml/features
features:install keycloak
----

. Install the corresponding Jetty adapter. Since the artifacts are available directly in the JBoss Fuse `system` directory, you do not need to use the Maven repository.

