== Before You Begin

=== Comparison: {project_openshift_product_name} Image and Red Hat Single Sign-On
The {project_openshift_product_name} image version number {project_version} is based on {project_name} {project_version}. There are some differences in functionality between the {project_openshift_product_name} image and {project_name}:

* The {project_openshift_product_name} image includes all of the functionality of {project_name}. In addition, the {project_name}-enabled JBoss EAP image automatically handles OpenID Connect or SAML client registration and configuration for *_.war_* deployments that contain *<auth-method>KEYCLOAK</auth-method>* or *<auth-method>KEYCLOAK-SAML</auth-method>* in their respective *web.xml* files.

=== Version Compatibility and Support
See the xPaaS part of the https://access.redhat.com/articles/2176281[OpenShift and Atomic Platform Tested Integrations page] for details about OpenShift image version compatibility.

=== Deprecated Image Streams and Application Templates for {project_openshift_product_name}

[IMPORTANT]
====
The {project_openshift_product_name} image version number 7.0 and 7.1 are deprecated and they will no longer receive updates of image and application templates.

*To deploy new applications, it is recommended to use the version 7.2 or {project_version} of the {project_openshift_product_name} image along with the application templates specific to these image versions.*
====

=== Initial Setup
The Tutorials in this guide follow on from and assume an OpenShift instance similar to that created by performing https://docs.openshift.com/container-platform/latest/install/index.html[the installation of the OpenShift Container Platform cluster].

[IMPORTANT]
====
For information related to updating the existing database when migrating {project_openshift_product_name} image from previous versions to version {project_version}, see the xref:upgrading-sso-db-from-previous-version[Updating Existing Database when Migrating {project_openshift_product_name} Image to a new version] section.
====
