// Module included in the following assemblies:
//
// server_admin/topics/users.adoc

[id="proc-searching-user_{context}"]
= Searching for a user

Search for a user to view detailed information about the user, such as the user's groups and roles. 

.Prerequisite
* You are in the realm where the user exists.

.Procedure
. Click *Users* in the main menu. This *Users* page is displayed.
. Type the full name, last name, first name, or email address of the user you want to search for in the search box. The search returns all users who match your criteria.  
. Alternatively, you can click *View all users* to list every user in the system.  
+
NOTE: This action searches only the local {project_name} database and not the federated database, such as LDAP. The backends for federated databases do not have a pagination mechanism that enables searching for users. 
+
.. To search users from a federated backend, the user list must be synced into the {project_name} database. Adjust the search criteria to sync the backend users to the {project_name} database.
+
.. Alternatively, click the *User Federation* in the left menu.
... To apply changes to a selected user, click *Sync changed users* on the page with your federation provider.
... To apply changes to all users in the database, click *Sync all users* on the page with your federation provider.

.Additional resources
* For more information on user federation, see <<_user-storage-federation,User Federation>>.
