// Module included in the following assemblies:
//
// server_admin/topics/users.adoc

[id="proc-setting-password-user_{context}"]
= Setting a password for a user

[role="_abstract"]
If a user does not have a password, or if the password has been deleted, the *Set Password* section is displayed.

If a user already has a password, it can be reset in the *Reset Password* section.

.Procedure
. Click *Users* in the menu. The *Users* page is displayed.
. Select a user.
. Click the *Credentials* tab.
. Type a new password in the *Set Password* section.
. Click *Set Password*.
+
NOTE: If *Temporary* is *ON*, the user must change the password at the first login. To allow users to keep the password supplied, set *Temporary* to *OFF.*  The user must click *Set Password* to change the password.

= Requesting a user reset a password

You can also request that the user reset the password.

.Procedure

. Click *Users* in the menu. The *Users* page is displayed.
. Select a user.
. Click the *Credentials* tab.
. Click *Credential Reset*.
. Select *Update Password* from the list.
. Optionally, you can set the validity of the email link. This is set to the default preset in the *Tokens* tab in *Realm Settings*.
. Optionally, select a *Client* to perform the action in the context of a specific application.
. Optionally, enter a *Redirect URI* to redirect the user back to the application after the action is completed. The URI must be a valid redirect URI of the selected client.
. Click *Send Email*. The sent email contains a link that directs the user to the *Update Password* window.
