<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="Deploy Multi-AZ AWS Aurora"
summary="Building block for a database"
preview="true"
tileVisible="false" >

This describes how to deploy an Aurora regional deployment of a PostgreSQL instance across multiple availability-zones to tolerate one or more availability-zone failures in a given AWS region.

This is intended to be used with the setup described in the <@links.ha id="concepts-active-passive-sync"/> {section}.
Use it together with the other building blocks outlined in the <@links.ha id="bblocks-active-passive-sync"/> {section}.

include::partials/blueprint-disclaimer.adoc[]

== Architecture

Aurora DB clusters consist of multiple Aurora DB instances, with one instance designated as the primary writer and all others as backup readers.
To ensure high availability in the event of availability zone failures, Aurora allows DB instances to be deployed across multiple zones in a single AWS region.
In the event of a failure on the availability-zone hosting the Primary DB instance, Aurora automatically heals itself and promotes a reader instance from a non-failed availability-zone to be the new writer instance.

.Aurora Multiple Availability Zone Deployment
image::high-availability/aurora-multi-az.dio.svg[]

See the https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html[AWS Aurora documentation] for more details on the semantics provided by Aurora DBs.

This follows AWS best-practices and creates a private Aurora DB not exposed to the Internet.
To access the database from a ROSA cluster, <<establish-peering-connections-with-rosa-clusters,establish a peering connection between the database and the ROSA cluster>>.

== Procedure

The following procedure is split into two parts.
First, we create an Aurora Multi-AZ DB cluster with the name "keycloak-aurora" in eu-west-1. Then we create a peering connection between our ROSA cluster(s) and the Aurora VPC to allow applications deployed on the ROSA clusters to be able to establish connections with the DB.

=== Create Aurora DB Cluster

include::partials/aurora/aurora-multiaz-create-procedure.adoc[]

[#establish-peering-connections-with-rosa-clusters]
=== Establish Peering Connections with ROSA clusters

The following steps must be repeated for each ROSA cluster that contains a {project_name} deployment.

include::partials/aurora/aurora-create-peering-connections.adoc[]

== Verifying the connection

include::partials/aurora/aurora-verify-peering-connections.adoc[]

== Deploying {project_name}

Now that an Aurora DB has been established and linked with all of your ROSA clusters, the next step is to deploy {project_name} as described in the <@links.ha id="deploy-keycloak-kubernetes" /> {section} with the JDBC url configured to use the Aurora DB writer endpoint.
To do this, create a `{project_name}` CR with the following adjustments:

. Update `spec.db.url` to be `jdbc:postgresql://$HOST:5432/keycloak` where `$HOST` is the
<<aurora-writer-url, Aurora writer endpoint URL>>.

. Ensure that the Secrets referenced by `spec.db.usernameSecret` and `spec.db.passwordSecret` contain usernames and passwords defined when creating Aurora.

</@tmpl.guide>
