<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>
<#import "/templates/profile.adoc" as profile>

<@tmpl.guide
title="High availability overview"
summary="Explore the different {project_name} high-availability architectures" >

{project_name} supports different high-availability architectures, allowing system administrators to pick the deployment type most suitable
for their needs. Ease of deployment, cost and fault-tolerance guarantees are important considerations when determining the correct architecture
for your deployments.

== Architectures

The following architectures are supported by {project_name}.

=== Single cluster

Deploy {project_name} in a single cluster, optionally "stretched" across multiple availability-zones, using <@links.ha id="single-cluster-introduction" />.

Advantages::
* No external dependencies
* Deployment in a single {kubernetes} cluster or a set of virtual machines with transparent networking
* Tolerate availability-zone failures if deployed to multiple availability zones

Disadvantages::
* {kubernetes} cluster is a single point of failure:
** Control-plane failures could impact all {project_name} pods

=== Multi cluster

Connect two {project_name} clusters deployed for example in different {kubernetes} clusters in two availability zones to increase availability using <@links.ha id="multi-cluster-introduction" />.

Advantages::
* Tolerate availability-zone failure
* Tolerate {kubernetes} cluster failure
* Bridge two networks that do not offer transparent networking
* Regulatory compliance when distinct deployments are required

Disadvantages::
* Complexity:
** External load-balancer required
** Separate {jdgserver_name} cluster required on each site
* Cost:
** Additional load-balancer required
** Additional compute is required for external {jdgserver_name} clusters
** Two {kubernetes} control-planes must be provisioned
* Not supported with three or more availability zones

=== Next Steps

To learn more about the different high-availability architectures, please consult the individual guides.

<@profile.ifCommunity>
* <@links.ha id="single-cluster-introduction" />
* <@links.ha id="multi-cluster-introduction" />
</@profile.ifCommunity>

</@tmpl.guide>
