package org.keycloak.protocol.oidc.rar;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiFunction;

import org.keycloak.models.ClientSessionContext;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.UserSessionModel;
import org.keycloak.provider.ProviderFactory;
import org.keycloak.representations.AccessTokenResponse;
import org.keycloak.representations.AuthorizationDetailsJSONRepresentation;
import org.keycloak.util.JsonSerialization;

import com.fasterxml.jackson.core.type.TypeReference;
import org.jboss.logging.Logger;

public class AuthorizationDetailsProcessorManager {

    private static final Logger logger = Logger.getLogger(AuthorizationDetailsProcessorManager.class);

    private final KeycloakSession session;

    public AuthorizationDetailsProcessorManager(KeycloakSession session) {
        this.session = session;
    }

    public List<AuthorizationDetailsJSONRepresentation> processAuthorizationDetails(UserSessionModel userSession, ClientSessionContext clientSessionCtx,
                                                                                    String authorizationDetailsParam) throws InvalidAuthorizationDetailsException {
        return processAuthorizationDetailsInternal(authorizationDetailsParam,
                (processor, authzDetail) -> processor.process(userSession, clientSessionCtx, authzDetail));
    }


    public List<AuthorizationDetailsJSONRepresentation> processStoredAuthorizationDetails(UserSessionModel userSession,
                                                                                          ClientSessionContext clientSessionCtx,
                                                                                          String authorizationDetailsParam) throws InvalidAuthorizationDetailsException {
        return processAuthorizationDetailsInternal(authorizationDetailsParam,
                (processor, authzDetail) ->
                        processor.processStoredAuthorizationDetails(userSession, clientSessionCtx, authzDetail));
    }


    public List<AuthorizationDetailsJSONRepresentation> handleMissingAuthorizationDetails(UserSessionModel userSession, ClientSessionContext clientSessionCtx) {
        List<AuthorizationDetailsJSONRepresentation> allAuthzDetails = new ArrayList<>();
        Map<String, ResolvedProcessor> processors = getAuthorizationDetailsProcessorMap();
        // Apply the same collision policy as for explicit authorization_details: only processors that won at least one
        // type are asked, and details of a type owned by another processor are dropped, so that subsequent hooks
        // never dispatch details generated by one processor to a different one.
        processors.values().stream().distinct().forEach(resolved -> {
            List<? extends AuthorizationDetailsJSONRepresentation> authzDetails = resolved.processor().handleMissingAuthorizationDetails(userSession, clientSessionCtx);
            if (authzDetails == null) {
                return;
            }
            for (AuthorizationDetailsJSONRepresentation authzDetail : authzDetails) {
                ResolvedProcessor owner = processors.get(authzDetail.getType());
                if (owner != null && owner.processor() != resolved.processor()) {
                    logger.debugf("Ignoring authorization_details of type '%s' generated by provider '%s', as this type is handled by provider '%s'.",
                            authzDetail.getType(), resolved.factoryId(), owner.factoryId());
                    continue;
                }
                allAuthzDetails.add(authzDetail);
            }
        });
        return allAuthzDetails;
    }

    public void validateAuthorizationDetail(String authorizationDetailsParam) {
        processAuthorizationDetailsInternal(authorizationDetailsParam, AuthorizationDetailsProcessor::validateAuthorizationDetail);
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    public void afterAuthorizationDetailsProcessed(UserSessionModel userSession,
                                                   ClientSessionContext clientSessionCtx,
                                                   List<AuthorizationDetailsJSONRepresentation> authorizationDetailsResponse) throws InvalidAuthorizationDetailsException {
        Map<String, ResolvedProcessor> processors = getAuthorizationDetailsProcessorMap();
        for (AuthorizationDetailsJSONRepresentation authzDetailResponse : authorizationDetailsResponse) {
            AuthorizationDetailsProcessor processor = findProcessorForAuthorizationDetails(processors, authzDetailResponse);
            processor.afterAuthorizationDetailsProcessed(userSession, clientSessionCtx, processor.narrowRepresentation(authzDetailResponse));
        }
    }

    /**
     * Sanitize authorization details before they are sent as part of the Token Response
     * https://github.com/keycloak/keycloak/issues/50079
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    public void sanitizeBeforeSendingTokenResponse(AccessTokenResponse tokenResponse) {
        if (tokenResponse.getAuthorizationDetails() != null) {
            List<AuthorizationDetailsJSONRepresentation> outAuthzDetails = new ArrayList<>();
            Map<String, ResolvedProcessor> processors = getAuthorizationDetailsProcessorMap();
            for (AuthorizationDetailsJSONRepresentation authzDetail : tokenResponse.getAuthorizationDetails()) {
                AuthorizationDetailsProcessor processor = findProcessorForAuthorizationDetails(processors, authzDetail);
                AuthorizationDetailsJSONRepresentation subAuthzDetail = processor.narrowRepresentation(authzDetail);
                outAuthzDetails.add(processor.sanitizeBeforeSendingTokenResponse(subAuthzDetail));
            }
            tokenResponse.setAuthorizationDetails(outAuthzDetails);
        }
    }

    // Private ---------------------------------------------------------------------------------------------------------

    /**
     * A processor selected to handle one or more authorization_details types, together with the id of the
     * {@link ProviderFactory} it was created from, so that log messages can refer to the configured provider.
     */
    private record ResolvedProcessor(String factoryId, AuthorizationDetailsProcessor<?> processor) {
    }

    /**
     * Builds a lookup map from authorization_details "type" to the processor handling it. A single processor may support
     * more than one type via {@link AuthorizationDetailsProcessor#getSupportedTypes()}, so the mapping is driven by the
     * supported types rather than by the {@link ProviderFactory#getId() provider id}. Processors for which
     * {@link AuthorizationDetailsProcessor#isSupported()} is false are left out, consistent with the types advertised
     * in the discovery document, so that a disabled processor neither handles requests nor shadows an enabled one. If
     * multiple supported processors claim the same type, the one whose factory has the higher
     * {@link ProviderFactory#order() order} wins.
     * <p>
     * The map is resolved per request because {@link AuthorizationDetailsProcessor#isSupported()} may depend on the
     * current context (for example the realm). Collisions are therefore only reported at debug level, as an intentional
     * override would otherwise be logged on every request.
     * <p>
     * The returned map preserves processor priority: iterating its values yields the processors in descending order.
     */
    private Map<String, ResolvedProcessor> getAuthorizationDetailsProcessorMap() {
        Map<String, ResolvedProcessor> processorsByType = new LinkedHashMap<>();
        session.getKeycloakSessionFactory()
                .getProviderFactoriesStream(AuthorizationDetailsProcessor.class)
                .sorted((f1, f2) -> Integer.compare(f2.order(), f1.order()))
                .forEach(factory -> {
                    AuthorizationDetailsProcessor<?> processor = (AuthorizationDetailsProcessor<?>) session.getProvider(AuthorizationDetailsProcessor.class, factory.getId());
                    if (!processor.isSupported()) {
                        return;
                    }
                    ResolvedProcessor resolved = new ResolvedProcessor(factory.getId(), processor);
                    for (String supportedType : processor.getSupportedTypes()) {
                        ResolvedProcessor existing = processorsByType.putIfAbsent(supportedType, resolved);
                        if (existing != null) {
                            logger.debugf("Multiple AuthorizationDetailsProcessor providers support authorization_details type '%s'. Using provider '%s' and ignoring provider '%s'.",
                                    supportedType, existing.factoryId(), factory.getId());
                        }
                    }
                });
        return processorsByType;
    }

    private List<AuthorizationDetailsJSONRepresentation> processAuthorizationDetailsInternal(String authorizationDetailsParam,
                                                                                             BiFunction<AuthorizationDetailsProcessor<?>, AuthorizationDetailsJSONRepresentation, AuthorizationDetailsJSONRepresentation> function) throws InvalidAuthorizationDetailsException {

        List<AuthorizationDetailsJSONRepresentation> authzDetails = parseAuthorizationDetails(authorizationDetailsParam);
        if (authzDetails.isEmpty()) {
            throw new InvalidAuthorizationDetailsException("Authorization_Details parameter cannot be empty");
        }

        Map<String, ResolvedProcessor> processors = getAuthorizationDetailsProcessorMap();

        List<AuthorizationDetailsJSONRepresentation> authzResponses = new ArrayList<>();
        for (AuthorizationDetailsJSONRepresentation authzDetail : authzDetails) {
            AuthorizationDetailsProcessor<?> processor = findProcessorForAuthorizationDetails(processors, authzDetail);
            AuthorizationDetailsJSONRepresentation response = function.apply(processor, authzDetail);
            if (response != null) {
                authzResponses.add(response);
            } else {
                logger.debugf("Null response returned by authorization processor " + processor + " for given authorization details");
            }
        }

        return authzResponses;
    }

    private AuthorizationDetailsProcessor<?> findProcessorForAuthorizationDetails(Map<String, ResolvedProcessor> processors, AuthorizationDetailsJSONRepresentation authzDetail) {
        if (authzDetail.getType() == null) {
            throw new InvalidAuthorizationDetailsException("Authorization_Details parameter provided without type: " + authzDetail);
        }
        ResolvedProcessor resolved = processors.get(authzDetail.getType());
        if (resolved == null) {
            String errorDetails = String.format("Unsupported type '%s' of authorization_details parameter supplied in the request. Supported values: %s",
                    authzDetail.getType(), processors.keySet());
            logger.warn(errorDetails);
            throw new InvalidAuthorizationDetailsException(errorDetails);
        }
        return resolved.processor();
    }

    private List<AuthorizationDetailsJSONRepresentation> parseAuthorizationDetails(String authorizationDetailsParam) {
        try {
            return JsonSerialization.readValue(authorizationDetailsParam, new TypeReference<>() {});
        } catch (Exception e) {
            logger.warnf(e, "Cannot parse authorization_details: %s", authorizationDetailsParam);
            throw new InvalidAuthorizationDetailsException("Invalid authorization_details: " + authorizationDetailsParam);
        }
    }
}
