team/cloud-native:
  - area/admin/cli
  - area/dist/quarkus
  - area/operator

team/continuous-testing:
  - area/ci
  - area/testsuite

team/core-clients:
  - area/adapter/fuse
  - area/adapter/java-cli
  - area/adapter/jee
  - area/adapter/jee-saml
  - area/adapter/spring
  - area/authentication
  - area/authentication/webauthn
  - area/login/ui
  - area/oidc
  - area/oid4vc
  - area/saml

team/core-iam:
  - area/admin/fine-grained-permissions
  - area/authorization-services
  - area/identity-brokering
  - area/user-profile

team/core-shared:
  - area/account/api
  - area/admin/api
  - area/admin/client-java
  - area/core
  - area/import-export
  - area/infinispan
  - area/ldap
  - area/storage
  - area/token-exchange

team/ui:
  - area/account/ui
  - area/adapter/javascript
  - area/admin/client-js
  - area/admin/ui
  - area/welcome/ui

team/community:
  - area/translations

team/core:
team/store:

no-team:
  - area/docs
  - area/dependencies
