
=== Downloading, Building, and Deploying Application Code

You must have the following installed on your machine and available in your PATH before you continue:

* Java JDK 8
* Apache Maven 3.1.1 or higher
* Git

ifeval::[{project_community}==true]
NOTE: You can obtain the code by cloning the {quickstartRepo_name} repository at {quickstartRepo_link}. The quickstarts are designed to work with the most recent Keycloak release.

endif::[]

ifeval::[{project_product}==true]
NOTE: You can obtain the code by cloning the repository at {quickstartRepo_link}. Use the branch matching the version of {project_name} in use.

endif::[]

Make sure your {appserver_name} application server is started before you continue.

To download, build, and deploy the code, complete the following steps.

.Clone Project
[source, subs="attributes"]
----
$ git clone {quickstartRepo_link}
$ cd {quickstartRepo_dir}/app-profile-jee-vanilla
$ mvn clean wildfly:deploy
----

During installation, you will see some text scroll by in the application server console window.

To confirm that the application is successfully deployed, go to http://localhost:8080/vanilla and a login page should appear.

NOTE: If you click *Login*, the browser will pop up a BASIC auth login dialog. However, the application is not yet secured by any identity provider, so anything you enter in the dialog box will result in a `Forbidden` message being sent back by the server. You can confirm that the application is currently secured via `BASIC` authentication by finding the setting in the application's `web.xml` file. 

