
=== Installing the Client Adapter

Download the {appserver_name} distribution and extract it from the compressed file into a directory on your machine.

ifeval::[{project_community}==true]
Download the WildFly OpenID Connect adapter distribution from link:https://www.keycloak.org/downloads.html[keycloak.org].
endif::[]

ifeval::[{project_product}==true]
Download the RH-SSO-{project_version}-eap7-adapter.zip distribution.
endif::[]

Extract the contents of this file into the root directory of your {appserver_name} distribution.

Run the appropriate script for your platform:

.WildFly 10 and Linux/Unix
[source,bash,subs=+attributes]
----
$ cd bin
$ ./jboss-cli.sh --file=adapter-install-offline.cli
----

.WildFly 10 and Windows
[source,bash,subs=+attributes]
----
> cd bin
> jboss-cli.bat --file=adapter-install-offline.cli
----

ifeval::[{project_community}==true]
.Wildfly 11 and Linux/Unix
[source,bash,subs=+attributes]
----
$ cd bin
$ ./jboss-cli.sh --file=adapter-elytron-install-offline.cli
----

.Wildfly 11 and Windows
[source,bash,subs=+attributes]
----
> cd bin
> jboss-cli.bat --file=adapter-elytron-install-offline.cli
----
endif::[]

NOTE: This script will make the necessary edits to the `.../standalone/configuration/standalone.xml` file of your app server distribution. 

Start the application server.

.Linux/Unix
[source,bash,subs=+attributes]
----
$ .../bin/standalone.sh
----

.Windows
[source,bash,subs=+attributes]
----
> ...\bin\standalone.bat
----
