
=== Installing the Client Adapter

Download the {{book.appserver.name}} distribution and unzip
it into a directory on your machine.

{% if book.community %}
Next download the WildFly OpenID Connect adapter distribution from link:http://www.keycloak.org/downloads.html[keycloak.org].
{% endif %}

{% if book.product %}
Next download the RH-SSO-{{book.project.version}}-eap7-adapter.zip distribution.
{% endif %}

Unzip this file into the root directory of your {{book.appserver.name}} distribution.

Next perform the following actions:

.WildFly 10 and Linux/Unix
[source]
----
$ cd bin
$ ./jboss-cli.sh --file=adapter-install-offline.cli
----

.WildFly 10 and Windows
[source]
----
> cd bin
> jboss-cli.bat --file=adapter-install-offline.cli
----

{% if book.community %}
.Wildfly 11 and Linux/Unix
[source]
----
$ cd bin
$ ./jboss-cli.sh --file=adapter-elytron-install-offline.cli
----

.Wildfly 11 and Windows
[source]
----
> cd bin
> jboss-cli.bat --file=adapter-elytron-install-offline.cli
----
{% endif %}

This script will make the appropriate edits to the _.../standalone/configuration/standalone.xml_ file of your app
server distribution.  Finally, boot the application server.

.Linux/Unix
[source]
----
$ .../bin/standalone.sh
----

.Windows
[source]
----
> ...\bin\standalone.bat
----
