vulnerabilities:
  - cveId: CVE-2024-6485
    packageName: bootstrap
    statement: Not affected, Bootstrap JavaScript component not distributed
  - cveId: CVE-2025-1647
    packageName: bootstrap
    statement: Not affected, Bootstrap JavaScript component not distributed
  - cveId: CVE-2026-45292
    packageName: io.opentelemetry:opentelemetry-api
    statement: Workaround applied (won't be upgraded in Quarkus 3.33.x)
    gitHubIssue: https://github.com/keycloak/keycloak/issues/49570

