<#import "/templates/guide.adoc" as tmpl>

<@tmpl.guide
title="Troubleshooting performance issues using Java Flight Recorder (JFR)"
summary="Create Java Flight Recorder (JFR) recordings of a {project_name} server to diagnose performance issues"
>

== What is Java Flight Recorder

Java Flight Recorder (JFR) is a standard monitoring tool for collecting diagnostic and profiling data about a running Java application. It is built into a JVM and designed to have a low performance impact.

JFR can be started on JVM startup by providing parameters via the `-XX:StartFlightRecording` argument, or it can be started later during application runtime by sending the `JFR.start` command using the `jcmd` tool.

Recording can either be started in a continuous mode in which case the `JFR.dump` command is needed to export the diagnostic data into a file, or it can be started in a fixed-time mode, in which case the data will be exported automatically after the requested interval elapses.

This guide further demonstrates creating a fixed-time flight recording using the `jcmd` tool.

=== Security considerations

Some of the diagnostic data collected by Java Flight Recorder may be security-sensitive.

WARNING: It is not recommended to share JFR recordings without sanitizing them for potentially sensitive information.

There are several approaches to sanitizing a JFR recording:

* Proactively, by disabling the collection of certain types of data when starting a JFR recording. This can be done by using custom JFR settings. See the <<create-a-fixed-time-recording>> section on how to apply custom settings.
* Retroactively, by scrubbing a recording for certain types of data after it has been saved to a file. This can be done by the `jfr scrub` command, either by excluding certain types of data, or by including only those types of data that are relevant for investigating a particular performance problem and known to be safe. See the <<scrub-sensitive-data>> section for details.

== Find the {project_name} server process

The `jcmd` tool can use a PID or a main class to identify the target process:
[source]
----
jcmd <PID|main-class> <diagnostic-command> ...
----

Running the `jcmd` command without any arguments will list all Java processes on the system with their PIDs and main classes:
[source]
----
jcmd
----

Example output:
[source]
----
897052 jdk.jcmd/sun.tools.jcmd.JCmd
896224 io.quarkus.bootstrap.runner.QuarkusEntryPoint start ... #<1>
----
<1> Assuming {project_name} is the only Quarkus-based application running on the system, its PID in this example would be `896224`. It is also possible to use the main class `QuarkusEntryPoint` instead of the PID.

Example: Running a `JFR.check` diagnostic command using the PID:
[source]
----
jcmd 896224 JFR.check
----

Example: Running a `JFR.check` diagnostic command using the main class:
[source]
----
jcmd QuarkusEntryPoint JFR.check
----

Example output:
[source]
----
896224:
No available recordings.

Use jcmd 896224 JFR.start to start a recording.
----

[[create-a-fixed-time-recording]]
== Create a fixed-time recording

A fixed-time recording can be created by executing the `JFR.start` command with the `duration` parameter. After the requested interval elapses the recording will be stopped and its data automatically dumped into a file.

[source]
----
jcmd QuarkusEntryPoint JFR.start \
  duration=2m \ #<1>
  settings=profile \ #<2>
  filename=recording.jfr #<3>
----
<1> Intended duration of the recording.
<2> Name of a JFR configuration file. A Java installation comes with two configurations in the `$JAVA_HOME/lib/jfr/` directory: `default.jfc` and `profile.jfc`.
+
The `default` configuration has a lower performance overhead and is suitable for continuous recording. The `profile` configuration provides more diagnostic data but has a higher impact on performance. It is recommended only for short periods of time. It is also possible to create a custom configuration using `jfr configure --interactive` command. For configuration files outside of the default location it is necessary to provide a full path.
<3> The `filename` parameter is optional. If not provided the name will be generated automatically based on PID and timestamp. If an absolute path is not provided the file will be created in the current working directory of the target application.

Use the `JFR.check` command shortly after to verify that the recording was started:
[source]
----
jcmd QuarkusEntryPoint JFR.check
----

Expected output (example):
[source]
----
896224:
Recording 1: name=1 duration=2m (running)
----

== View and manipulate a dumped recording

IMPORTANT: Once a recording is dumped into a file it is important to sanitize it for potentially sensitive data using the `jfr scrub` command. See the <<scrub-sensitive-data>> section below.

Once the recording is dumped into a file it can be viewed and manipulated using the standard `jfr` tool.

To print the content of a recording in a human-readable form use the `jfr print` command:
[source]
----
jfr print recording.jfr
----

To get a general overview of the content use the `jfr summary` command:
[source]
----
jfr summary recording.jfr
----

Example output:
[source]
----

 Version: 2.1
 Chunks: 1
 Start: YYYY-MM-DD HH:mm:ss (UTC)
 Duration: 120 s

 Event Type                              Count  Size (bytes)
=============================================================
 jdk.NativeMethodSample                   5919         82597
 jdk.ModuleExport                         2134         27601
 jdk.ThreadPark                           2082         73000
 jdk.JavaMonitorWait                       781         22715
 jdk.BooleanFlag                           494         16124
 jdk.ActiveSetting                         376         10893
 jdk.Checkpoint                            168        136675
 jdk.ModuleRequire                         160          1920
 jdk.LongFlag                              137          4674
 jdk.ThreadAllocationStatistics            122          1604
 jdk.CPULoad                               120          2520
 jdk.ClassLoadingStatistics                120          1560
 jdk.CompilerStatistics                    120          3840
 jdk.ExceptionStatistics                   120          1440
 jdk.JavaThreadStatistics                  120          1560
 ⋯
----

To display aggregated content of the recording in a tabular form use the `jfr view` command.

To get a list of available views use `jfr view types` command:
[source]
----
jfr view types recording.jfr
----

To get a specific view use `jfr view <event-type>` command. For example:
[source]
----
jfr view CPULoad recording.jfr
----

Example output:
[source]
----
                                     CPU Load

Time                         JVM User           JVM System           Machine Total
------------------ ------------------ -------------------- -----------------------
10:32:07                        0.02%                0.01%                   4.26%
10:32:08                        0.05%                0.00%                   2.25%
10:32:09                        0.10%                0.05%                   2.20%
10:32:10                        0.05%                0.00%                   3.05%
10:32:11                        0.05%                0.00%                   2.56%
10:32:12                        0.05%                0.05%                   2.55%
 ⋯
----

[[scrub-sensitive-data]]
== Scrub sensitive data from a flight recording

Once a recording is dumped into a file it is important to scrub it for potentially sensitive data to prevent security leaks. This can be done using a standard `jfr scrub` command.

=== Exclude sensitive information

Use `jfr scrub --exclude-events ⋯` to exclude security-sensitive data.

For {project_name}, high-risk content collected by JFR can be removed by the following command:
[source]
----
jfr scrub \
  --exclude-events jdk.InitialEnvironmentVariable,jdk.JVMInformation,jdk.OldObjectSample \
  recording.jfr recording-scrubbed.jfr
----

See below for events that can reveal sensitive information:

[%autowidth]
|===
| JFR Event Name | Risk | Explanation

| `jdk.InitialEnvironmentVariable` | High | Environment variables can contain secrets passed to {project_name} during startup. For example: `KC_DB_PASSWORD`.
| `jdk.JVMInformation` | High | JVM information can contain secrets in CLI arguments passed to {project_name} during startup. For example: `--db-password`.
| `jdk.OldObjectSample` | High | Serialized Java objects can include sensitive in-memory information.
| `jdk.InitialSystemProperty` | Low | {project_name} by default does not pass sensitive information here.
|===

WARNING: Other flight recorder events may contain information like host names, file paths or URL parameters.
To analyze the contents for sensitive information, use `jfr print recording.jfr` or `jfr print --json recording.jfr` to review the contents.
You can also use `jfr scrub --include-events ...` to only share a subset of the events for troubleshooting.

=== Include only specific information

Use `jfr scrub --include-events ⋯` to only include data relevant to a particular perfromance problem.

Example:
[source]
----
jfr scrub \
  --include-events jdk.ExecutionSample,jdk.CPULoad,jdk.GarbageCollection,jdk.GCHeapSummary,jdk.GCPhasePause,jdk.MetaspaceSummary,jdk.JavaMonitorEnter,jdk.ThreadPark \
  recording.jfr recording-scrubbed.jfr
----

[%autowidth]
|===
| Diagnostics Area	| JFR Event Name	| What It Troubleshoots	| Why It Is Safe

| CPU Profiling	| `jdk.ExecutionSample`, `jdk.CPULoad`	| Finds "hot methods," high CPU utilization, and thread distribution.	| Captures sample counts, CPU percentages, and stack frames (method names), but no variable data or string values.
| Garbage Collection	| `jdk.GarbageCollection`, `jdk.GCHeapSummary`, `jdk.GCPhasePause`, `jdk.MetaspaceSummary`	| Heavy GC pauses, memory exhaustion, improper heap sizing.	| Strictly statistical. It records numbers, byte sizes, timestamps, and durations. It never looks at object contents.
| Threading & Locks	| `jdk.JavaMonitorEnter`, `jdk.ThreadPark`	| Thread blockages, lock contention, and concurrency bottlenecks.	| Only captures the duration a thread spent waiting to acquire a lock and the class name of the monitor object.
|===

</@tmpl.guide>
