<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="Metrics for troubleshooting {project_name} deployment"
summary="Learn about metrics that can indicate where the issue is, for example, when service level objective is not met"
>

For a running {project_name} deployment it is important to understand how the system performs and whether it meets your service level objectives (SLOs).
For more details on SLOs, proceed to the <@links.observability id="keycloak-service-level-indicators" /> {section}.

This guide will provide directions to answer the question: "What can I do when my SLOs are not met?".
{project_name} consists of more components where an issue or a wrong configuration of one of them can move your service level indicators to undesirable numbers.

A guidance provided by this guide is illustrated in the following example.

_My latency service level objective is not met._
_From the listed metrics it is possible to observe the following._

. _{project_name}'s database connection pool is often exhausted and there are thread queuing for a connection to be retrieved from the pool._
. _{project_name}'s `users` cache hit ratio is at a low percentage, around 5%. This means only 1 out of 20 user searches is able to obtain user data from the cache and the rest needs to load it from the database._

__The guide would suggest two possible mitigation for this issue.
Increasing the `users` cache size to a higher number which would decrease the number of needed trips to the database.
Increasing the number of connections in the connection pool. This would need to be checked with metrics for your database and tuning it for higher load, for example, by increasing the number of available processors.
Note this guide focuses on {project_name} metrics and troubleshooting the database itself is out of scope.
__

Also note this guide provides a general guidance, you should always confirm the configuration change by conducting a performance test comparing the metrics in question for the old and the new configuration.

== Prerequisites

* Metrics need to be enabled for {project_name}. Follow <@links.observability id="configuration-metrics"/> {section} for more details.
* A monitoring system collecting the metrics.

== List of {project_name} key metrics

* <@links.observability id="metrics-for-troubleshooting-jvm"/>
* <@links.observability id="metrics-for-troubleshooting-database"/>
* <@links.observability id="metrics-for-troubleshooting-http"/>
* Single site metrics (without external {jdgserver_name})
** <@links.observability id="metrics-for-troubleshooting-clustering-and-network"/>
** <@links.observability id="metrics-for-troubleshooting-embedded-caches"/>
* Multiple sites metrics (as described in <@links.ha id="introduction"/>)
** <@links.observability id="metrics-for-troubleshooting-embedded-caches-multi-site"/>
** <@links.observability id="metrics-for-troubleshooting-external-infinispan-multi-site"/>


</@tmpl.guide>
