<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/kc.adoc" as kc>
<#import "/templates/options.adoc" as opts>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="Troubleshooting performance issues using JVM thread dumps"
summary="Capture JVM thread dumps of a {project_name} server to diagnose performance issues"
includedOptions="">

== What is a thread dump?

A JVM thread dump is a snapshot of the execution state of active threads within a Java Virtual Machine at a specific point in time.

Thread dumps are useful for diagnosing issues such as thread contention, deadlocks, CPU spikes, or stuck IO operations.

== How to capture a JVM thread dump

There are several ways to capture a thread dump. This guide uses `jcmd` as it provides the most straightforward command line experience.

The `jcmd` tool sends diagnostic commands to a running JVM. There are two commands relevant to capturing thread dumps: `Thread.print` and `Thread.dump_to_file`.

=== Using the `Thread.print` command

The following command prints a thread dump to the standard output.

[source]
----
jcmd <PID> Thread.print -l #<1>
----
<1> The `-l` option enables printing additional information about locks.

=== Using the `Thread.dump_to_file` command

The following command writes a thread dump to a file in a plain-text format.

[source]
----
jcmd <PID> Thread.dump_to_file threaddump.txt
----

The following command writes a thread dump to a file in the JSON format.

[source]
----
jcmd <PID> Thread.dump_to_file -format=json threaddump.json
----

Compared with the plain-text format the JSON output contains additional information about thread container hierarchy.

If the filename argument is not an absolute path the thread dumps will be created inside the current working directory of the target process. In case of {project_name} this would be inside the `bin/` directory.

=== Forming a comprehensive picture

Because thread dumps created by the `Thread.print` command lack detailed information about virtual threads, and thread dumps created by the `Thread.dump_to_file` command lack information about locks and object monitors (on JDK versions prior to JDK 25), and some additional JVM-internal and OS-specific information, it is recommended to create thread dumps using both the `Thread.print` and the `Thread.dump_to_file` commands in order to form a comprehensive picture about the state of the JVM.

== Finding PID of the {project_name} process

Running the `jcmd` command without parameters will list out Java processes running on the system, and their PIDs.

[source]
----
242551 io.quarkus.bootstrap.runner.QuarkusEntryPoint start ... #<1>
268778 jdk.jcmd/sun.tools.jcmd.JCmd
----
<1> Assuming {project_name} is the only Quarkus-based application running on the system its PID in this example would be `242551`.

== Collecting multiple samples

Because a single thread dump is just a snapshot of the JVM state at a particular point in time, it is recommended to capture multiple thread dumps over a period of time, for example 3-5 samples spaced 5-10 seconds apart.

</@tmpl.guide>
