import=common/keycloak

stylesCommon=vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css
styles=css/welcome.css

# When set to true, the user will be redirected to the Administration Console if an administrative users already exists.
redirectToAdmin=true
darkMode=true

kcDarkModeClass=pf-v5-theme-dark

# Aligned with the keycloak.v2 login theme
kcFormActionGroupClass=pf-v5-c-form__actions pf-v5-u-pt-xs
kcLoginMainHeaderDesc=pf-v5-c-login__main-header-desc gray-text
