StylesPath = ~/.vale/styles
MinAlertLevel = warning
Packages = https://github.com/jhradilek/asciidoctor-dita-vale/releases/latest/download/AsciiDocDITA.zip

[*.adoc]
BasedOnStyles = AsciiDocDITA

# The rules below are based on recommended practices and do not prevent
# successful conversion to DITA.  If your product is not bound by these
# guidelines, uncomment the following lines to disable them:
#AsciiDocDITA.CalloutList = NO
#AsciiDocDITA.ShortDescription = NO
#AsciiDocDITA.ConceptLink = NO

