parent=base
deprecatedMode=false
darkMode=true

kcDarkModeClass=pf-v5-theme-dark
contentHashPattern=assets/.*

title=Fidar Account
description=Manage your Fidar account, security, and connected applications.