
=== Important directories

The following are some important directories in the server distribution.

_bin/_::
  This contains various scripts to either boot the server or perform some other management action on the server.

_domain/_::
  This contains configuration files and working directory when running {project_name} in <<_domain-mode,domain mode>>.

_modules/_::
  These are all the Java libraries used by the server.

_standalone/_::
  This contains configuration files and working directory when running {project_name} in <<_standalone-mode,standalone mode>>.

_standalone/deployments/_::
  If you are writing extensions to {project_name}, you can put your extensions here.  See the link:{developerguide_link}[{developerguide_name}] for more information on this.

_themes/_::
  This directory contains all the html, style sheets, JavaScript files, and images used to display any UI screen displayed by the server.
  Here you can modify an existing theme or create your own.  See the link:{developerguide_link}[{developerguide_name}] for more information on this.
