
=== Installing the Keycloak server

The Keycloak Server has two downloadable distributions:

* `keycloak-{project_version}.[zip|tar.gz]`
+
This file is the server only distribution.  It contains nothing other than the scripts and binaries
to run the Keycloak Server. 

* `keycloak-overlay-{project_version}.[zip|tar.gz]`
+
This file is a WildFly add-on that you can use to install the Keycloak Server on top of an existing
WildFly distribution.  We do not support users who want to run their applications and Keycloak on the same server instance.

.Procedure

. To install the Keycloak server, run your operating system's `unzip` or `gunzip` and `tar` utilities on the `keycloak-{project_version}.[zip|tar.gz]` file.

. To install the Keycloak Service Pack, it must be installed on a different server instance.

 .. Change to the root directory of your WildFly distribution.
 .. Unzip the `keycloak-overlay-{project_version}.[zip|tar.gz]` file. 
 .. Open the bin directory in a shell.
 .. Run `./jboss-cli.[sh|bat] --file=keycloak-install.cli`.




