[[_installing_rpm]]

=== Installing RH-SSO from an RPM

NOTE: With Red Hat Enterprise Linux 7, the term channel was replaced with the term repository. In these instructions only the term repository is used.

You must subscribe to both the {appserver_name} {appserver_version} and RH-SSO {project_versionDoc} repositories before you can install RH-SSO from an RPM.

NOTE: You cannot continue to receive upgrades to EAP RPMs but stop receiving updates for RH-SSO.

[[subscribing_EAP_repo]]
==== Subscribing to the {appserver_name} {appserver_version} Repository

.Prerequisites

. Ensure that your Red Hat Enterprise Linux system is registered to your account using Red Hat Subscription Manager. For more information see the link:https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/quick_registration_for_rhel/index[Red Hat Subscription Management documentation].

. If you are already subscribed to another {appserver_name} repository, you must unsubscribe from that repository first.

Using Red Hat Subscription Manager, subscribe to the {appserver_name} {appserver_version} repository using the following command. Replace <RHEL_VERSION> with either 6 or 7 depending on your Red Hat Enterprise Linux version.

[source,bash,subs="attributes+"]
----
subscription-manager repos --enable=jb-eap-{appserver_version}-for-rhel-<RHEL_VERSION>-server-rpms --enable=rhel-<RHEL_VERSION>-server-rpms
----

==== Subscribing to the RH-SSO {project_versionDoc} Repository and Installing RH-SSO {project_versionDoc}

.Prerequisites

. Ensure that your Red Hat Enterprise Linux system is registered to your account using Red Hat Subscription Manager. For more information see the link:https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/quick_registration_for_rhel/index[Red Hat Subscription Management documentation].
. Ensure that you have already subscribed to the {appserver_name} {appserver_version} repository. For more information see xref:subscribing_EAP_repo[Subscribing to the {appserver_name} {appserver_version} repository].

To subscribe to the RH-SSO {project_versionDoc} repository and install RH-SSO {project_versionDoc}, complete the following steps:

. Using Red Hat Subscription Manager, subscribe to the RH-SSO {project_versionDoc} repository using the following command. Replace <RHEL_VERSION> with either 6 or 7 depending on your Red Hat Enterprise Linux version.
+
[source,bash,subs="attributes+"]
----
subscription-manager repos --enable=rh-sso-{project_versionDoc}-for-rhel-<RHEL-VERSION>-server-rpms
----

. Install RH-SSO from your subscribed RH-SSO {project_versionDoc} repository using the following command:

 yum groupinstall rh-sso7

Your installation is complete. The default RH-SSO_HOME path for the RPM installation is /opt/rh/rh-sso7/root/usr/share/keycloak.
