package org.keycloak.cookie;

import java.util.List;

import org.keycloak.Config;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.KeycloakSessionFactory;
import org.keycloak.provider.ProviderConfigProperty;
import org.keycloak.provider.ProviderConfigurationBuilder;

public class DefaultCookieProviderFactory implements CookieProviderFactory {

    private String cookiePrefix = "";

    @Override
    public CookieProvider create(KeycloakSession session) {
        return new DefaultCookieProvider(session, cookiePrefix);
    }

    @Override
    public void init(Config.Scope config) {
        String prefix = config.get("cookie-prefix");
        if (prefix != null) {
            cookiePrefix = prefix;
        }
    }

    @Override
    public void postInit(KeycloakSessionFactory factory) {
    }

    @Override
    public void close() {
    }

    @Override
    public String getId() {
        return "default";
    }

    @Override
    public List<ProviderConfigProperty> getConfigMetadata() {
        return ProviderConfigurationBuilder.create()
                .property()
                .name("cookie-prefix")
                .type("string")
                .helpText("A prefix to prepend to all cookie names generated by Keycloak. " +
                        "Useful for blue-green deployments or running multiple Keycloak instances on the same domain. " +
                        "Default is empty (no prefix).")
                .defaultValue("")
                .add()
                .build();
    }

}
