package org.keycloak.cookie;

import java.util.List;

import org.keycloak.Config;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.KeycloakSessionFactory;
import org.keycloak.provider.ProviderConfigProperty;
import org.keycloak.provider.ProviderConfigurationBuilder;

public class DefaultCookieProviderFactory implements CookieProviderFactory {

    public static final String COOKIE_PREFIX_CONFIG = "cookie-prefix";

    private String cookiePrefix = "";

    @Override
    public CookieProvider create(KeycloakSession session) {
        return new DefaultCookieProvider(session, cookiePrefix);
    }

    @Override
    public void init(Config.Scope config) {
        String prefix = config.get(COOKIE_PREFIX_CONFIG);
        if (prefix != null) {
            validateCookiePrefix(prefix);
            cookiePrefix = prefix;
        }
    }

    /**
     * Validates that the cookie prefix contains only characters allowed in cookie names per RFC 6265.
     * Rejects control characters, spaces, and cookie-delimiter characters: semicolon, comma, equals, backslash, and double-quote.
     */
    public static void validateCookiePrefix(String prefix) {
        if (prefix == null || prefix.isEmpty()) {
            return;
        }
        for (int i = 0; i < prefix.length(); i++) {
            char c = prefix.charAt(i);
            if (c <= 0x20 || c >= 0x7F || c == ';' || c == ',' || c == '=' || c == '"' || c == '\\') {
                throw new IllegalArgumentException(
                        "Invalid cookie prefix '" + prefix + "': contains illegal character '" + c + "' at position " + i +
                        ". Cookie prefixes must only contain printable ASCII characters excluding spaces, semicolons, commas, equals signs, double-quotes, and backslashes (per RFC 6265).");
            }
        }
    }

    @Override
    public void postInit(KeycloakSessionFactory factory) {
    }

    @Override
    public void close() {
    }

    @Override
    public String getId() {
        return "default";
    }

    @Override
    public List<ProviderConfigProperty> getConfigMetadata() {
        return ProviderConfigurationBuilder.create()
                .property()
                .name(COOKIE_PREFIX_CONFIG)
                .type("string")
                .helpText("A prefix to prepend to all cookie names generated by Keycloak. " +
                        "Useful for blue-green deployments or running multiple Keycloak instances on the same domain. " +
                        "Default is empty (no prefix).")
                .defaultValue("")
                .add()
                .build();
    }

}
