apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak-operator

resources:
- ../../kubernetes

configMapGenerator:
  # Local values for reuse in 'replacements', will not be published
  - literals:
      - Watch="JOSDK_ALL_NAMESPACES"
      - BindingKind="ClusterRoleBinding"
    name: replacements-values
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

replacements:
    # - sourceValue: JOSDK_ALL_NAMESPACES - later versions of kustomize will support this so a ConfigMap won't be needed
  - source:
      kind: ConfigMap
      name: replacements-values
      fieldPath: data.BindingKind
    targets:
      - select:
          kind: RoleBinding
        fieldPaths:
          - kind
  - source:
      kind: ConfigMap
      name: replacements-values
      fieldPath: data.Watch
    targets:
      - select:
          kind: Deployment
          name: keycloak-operator
        fieldPaths:
          - spec.template.spec.containers.0.env.[value=JOSDK_WATCH_CURRENT].value

patches:
- target:
    kind: Role
    name: keycloak-operator-role
  patch: |-
    - op: replace
      path: /kind
      value: ClusterRole
- target:
    kind: RoleBinding
    name: keycloak-operator-role-binding
  patch: |-
    - op: replace
      path: /kind
      value: ClusterRoleBinding
    - op: replace
      path: /roleRef/kind
      value: ClusterRole
    - op: remove
      path: /metadata/namespace
