version: "2.2"

networks:
    keycloak:
        ipam:
            config:
            - subnet: 10.0.1.0/24
    loadbalancing:
        ipam:
            config:
            - subnet: 10.0.2.0/24

services:
    
    mariadb:
        build: db/mariadb
        image: keycloak_test_mariadb:${KEYCLOAK_VERSION:-latest}
        cpuset: ${DB_CPUSET:-1}
        mem_limit: ${DB_MEMLIMIT:-1g}
        networks:
            - keycloak
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: keycloak
        ports:
            - "3306:3306"

    keycloak_lb:
        build: load-balancer/wildfly-modcluster
        image: keycloak_test_wildfly_modcluster:${KEYCLOAK_VERSION:-latest}
#        depends_on:
#            keycloak:
#                condition: service_healthy
        cpus: 1
        networks:
            - keycloak
#            - loadbalancing
        environment:
            PRIVATE_SUBNET: 10.0.1.0/24
#            PUBLIC_SUBNET: 10.0.2.0/24
            JAVA_OPTS: ${KEYCLOAK_LB_JVM_MEMORY:--Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m} -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
            HTTP_MAX_CONNECTIONS: ${KEYCLOAK_LB_HTTP_MAX_CONNECTIONS:-500}
            WORKER_IO_THREADS: ${KEYCLOAK_LB_WORKER_IO_THREADS:-2}
            WORKER_TASK_MAX_THREADS: ${KEYCLOAK_LB_WORKER_TASK_MAX_THREADS:-16}
        ports:
            - "8080:8080"


