#!/bin/bash
#
# Generates MIGRATION_CHECKLIST.md by comparing tests in the legacy testsuite
# against tests in the new test modules (tests/base and tests/webauthn).
# Each unmigrated test is scored by complexity: 🟢 easy, 🟡 mid, 🔴 complex.
#
# Usage: ./generate-checklist.sh
#
# Run from any directory — the script finds the project root automatically.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

LEGACY_DIR="$PROJECT_ROOT/testsuite/integration-arquillian/tests/base/src/test/java"
NEW_BASE_DIR="$PROJECT_ROOT/tests/base/src/test/java"
NEW_WEBAUTHN_DIR="$PROJECT_ROOT/tests/webauthn/src/test/java"
OUTPUT="$SCRIPT_DIR/MIGRATION_CHECKLIST.md"

if [ ! -d "$LEGACY_DIR" ]; then
    echo "ERROR: Legacy test directory not found: $LEGACY_DIR" >&2
    exit 1
fi

# Collect test class names from legacy and all new modules
legacy_tests=$(find "$LEGACY_DIR" -name "*Test.java" -exec basename {} .java \; | sort)

new_tests_combined=""
if [ -d "$NEW_BASE_DIR" ]; then
    new_tests_combined=$(find "$NEW_BASE_DIR" -name "*Test.java" -exec basename {} .java \;)
fi
if [ -d "$NEW_WEBAUTHN_DIR" ]; then
    webauthn_tests=$(find "$NEW_WEBAUTHN_DIR" -name "*Test.java" -exec basename {} .java \; 2>/dev/null || true)
    if [ -n "$webauthn_tests" ]; then
        new_tests_combined=$(printf '%s\n%s' "$new_tests_combined" "$webauthn_tests")
    fi
fi
new_tests=$(echo "$new_tests_combined" | sort -u)

legacy_count=$(echo "$legacy_tests" | wc -l | tr -d ' ')
new_count=$(echo "$new_tests" | grep -c . || echo 0)

# Count per new module
new_base_count=$(find "$NEW_BASE_DIR" -name "*Test.java" 2>/dev/null | wc -l | tr -d ' ')
new_webauthn_count=$(find "$NEW_WEBAUTHN_DIR" -name "*Test.java" 2>/dev/null | wc -l | tr -d ' ')

# Find tests that exist in both (migrated but legacy not yet deleted)
migrated_both=$(comm -12 <(echo "$legacy_tests") <(echo "$new_tests"))
migrated_both_count=$(echo "$migrated_both" | grep -c . || echo 0)

# Tests only in legacy (not yet migrated)
not_migrated=$(comm -23 <(echo "$legacy_tests") <(echo "$new_tests"))
not_migrated_count=$(echo "$not_migrated" | grep -c . || echo 0)

# Tests only in new (written directly in new framework)
new_only=$(comm -13 <(echo "$legacy_tests") <(echo "$new_tests"))
new_only_count=$(echo "$new_only" | grep -c . || echo 0)

# --- Complexity scoring function ---
# Returns: easy, mid, or complex
# Scoring:
#   +2 for UI (@Drone, @Page, @SecondBrowser)
#   +1 for testingClient usage
#   +2 for FlowUtil usage
#   +1 for server annotations (@EnableFeature, @EnableVault, @SetDefaultProvider, @ModelTest)
#   +1 for >500 lines
#   +1 for >1000 lines
# Score 0-1 = easy, 2-3 = mid, 4+ = complex
get_complexity() {
    local file="$1"
    local lines ui testing flowutil features score

    lines=$(wc -l < "$file" | tr -d ' ')
    ui=$(grep -cE "@Drone|@Page|@SecondBrowser" "$file" || true)
    testing=$(grep -c "testingClient" "$file" || true)
    flowutil=$(grep -c "FlowUtil" "$file" || true)
    features=$(grep -cE "@EnableFeature|@DisableFeature|@EnableVault|@SetDefaultProvider|@ModelTest" "$file" || true)

    score=0
    [ "$ui" -gt 0 ] && score=$((score + 2))
    [ "$testing" -gt 0 ] && score=$((score + 1))
    [ "$flowutil" -gt 0 ] && score=$((score + 2))
    [ "$features" -gt 0 ] && score=$((score + 1))
    [ "$lines" -gt 500 ] && score=$((score + 1))
    [ "$lines" -gt 1000 ] && score=$((score + 1))

    if [ "$score" -le 1 ]; then
        echo "easy"
    elif [ "$score" -le 3 ]; then
        echo "mid"
    else
        echo "complex"
    fi
}

# Pre-compute complexity for all unmigrated tests
declare -A test_complexity
easy_count=0
mid_count=0
complex_count=0
while read -r test; do
    file=$(find "$LEGACY_DIR" -name "${test}.java" | head -1)
    if [ -z "$file" ]; then continue; fi
    level=$(get_complexity "$file")
    test_complexity[$test]="$level"
    case "$level" in
        easy) easy_count=$((easy_count + 1)) ;;
        mid) mid_count=$((mid_count + 1)) ;;
        complex) complex_count=$((complex_count + 1)) ;;
    esac
done <<< "$not_migrated"

# Start generating the checklist
cat > "$OUTPUT" << 'HEADER'
# Migration Checklist

Auto-generated by `generate-checklist.sh`. Do not edit manually.

HEADER

echo "**Generated**: $(date -u '+%Y-%m-%d %H:%M UTC')" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Summary
cat >> "$OUTPUT" << EOF
## Summary

| Metric | Count |
|--------|-------|
| Legacy tests (testsuite/) | $legacy_count |
| New tests total | $new_count |
| — tests/base | $new_base_count |
| — tests/webauthn | $new_webauthn_count |
| Migrated (exists in both, legacy not yet deleted) | $migrated_both_count |
| Not yet migrated | $not_migrated_count |
| New-only (written directly in new framework) | $new_only_count |
| **Migration progress** | **$(( (new_count * 100) / (legacy_count + new_only_count) ))%** |

### Complexity Breakdown (unmigrated)

| Complexity | Count | Description |
|-----------|-------|-------------|
| 🟢 Easy | $easy_count | Simple admin API tests, no UI, no testingClient |
| 🟡 Mid | $mid_count | Some UI or testingClient or server annotations, moderate size |
| 🔴 Complex | $complex_count | UI + FlowUtil, large files, multiple complexity factors |

Scoring: +2 UI (@Drone/@Page), +2 FlowUtil, +1 testingClient, +1 server annotations, +1 >500 lines, +1 >1000 lines. Easy ≤1, Mid 2–3, Complex ≥4.

---

EOF

# Migrated but not cleaned up
if [ "$migrated_both_count" -gt 0 ]; then
    cat >> "$OUTPUT" << 'EOF'
## Migrated (legacy file not yet deleted)

These tests exist in both directories. The legacy copy should be deleted:

EOF
    echo "$migrated_both" | while read -r test; do
        legacy_path=$(find "$LEGACY_DIR" -name "${test}.java" | head -1 | sed "s|$PROJECT_ROOT/||")
        echo "- [x] \`$test\` — legacy: \`$legacy_path\`" >> "$OUTPUT"
    done
    echo "" >> "$OUTPUT"
    echo "---" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
fi

# Not yet migrated, grouped by category
cat >> "$OUTPUT" << 'EOF'
## Not Yet Migrated

EOF

# Build category → test mapping
declare -A categories
declare -A test_targets
while read -r test; do
    filepath=$(find "$LEGACY_DIR" -name "${test}.java" | head -1 | sed "s|$LEGACY_DIR/org/keycloak/testsuite/||")
    if [ -z "$filepath" ]; then
        continue
    fi
    category=$(echo "$filepath" | cut -d'/' -f1)
    # If the file is directly in testsuite/ (base classes), use "(root)"
    if echo "$filepath" | grep -q "^${test}.java$"; then
        category="(root)"
    fi
    if [ -z "${categories[$category]+x}" ]; then
        categories[$category]="$test"
    else
        categories[$category]="${categories[$category]}"$'\n'"$test"
    fi

    # Determine target module
    if [ "$category" = "webauthn" ]; then
        test_targets[$test]="→ tests/webauthn"
    else
        test_targets[$test]=""
    fi
done <<< "$not_migrated"

# Complexity emoji
complexity_emoji() {
    case "$1" in
        easy) echo "🟢" ;;
        mid) echo "🟡" ;;
        complex) echo "🔴" ;;
        *) echo "⚪" ;;
    esac
}

# Sort categories and output
for category in $(echo "${!categories[@]}" | tr ' ' '\n' | sort); do
    count=$(echo "${categories[$category]}" | wc -l | tr -d ' ')
    target_note=""
    if [ "$category" = "webauthn" ]; then
        target_note=" → tests/webauthn"
    fi
    echo "### $category ($count)$target_note" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "${categories[$category]}" | sort | while read -r test; do
        level="${test_complexity[$test]:-easy}"
        emoji=$(complexity_emoji "$level")
        suffix="${test_targets[$test]:-}"
        if [ -n "$suffix" ]; then
            echo "- [ ] $emoji \`$test\` $suffix" >> "$OUTPUT"
        else
            echo "- [ ] $emoji \`$test\`" >> "$OUTPUT"
        fi
    done
    echo "" >> "$OUTPUT"
done

echo "Generated $OUTPUT"
echo "  Legacy: $legacy_count | New: $new_count (base: $new_base_count, webauthn: $new_webauthn_count) | Not migrated: $not_migrated_count"
echo "  Complexity: easy=$easy_count mid=$mid_count complex=$complex_count"
