
=== Modifying the {project_name} datasource

You modify the existing datasource configuration that {project_name} uses
to connect it to your new external database.  You'll do
this within the same configuration file and XML block that you registered your JDBC driver in.  Here's an example
that sets up the connection to your new database:

.Declare Your JDBC Drivers
[source,xml,subs="attributes+"]
----
  <subsystem xmlns="{subsystem_datasources_xml_urn}">
     <datasources>
       ...
       <datasource jndi-name="java:jboss/datasources/KeycloakDS" pool-name="KeycloakDS" enabled="true" use-java-context="true">
           <connection-url>jdbc:postgresql://localhost/keycloak</connection-url>
           <driver>postgresql</driver>
           <pool>
               <max-pool-size>20</max-pool-size>
           </pool>
           <security>
               <user-name>William</user-name>
               <password>password</password>
           </security>
       </datasource>
        ...
     </datasources>
  </subsystem>
----

.Prerequisites

* You have already declared your JDBC driver.

.Procedure

. Search for the `datasource` definition for `KeycloakDS`.
+
You'll first need to modify the `connection-url`.  The
documentation for your vendor's JDBC implementation should specify the format for this connection URL value.

. Define the `driver` you will use.
+
This is the logical name of the JDBC driver you declared in the previous section of this
chapter.
+
It is expensive to open a new connection to a database every time you want to perform a transaction.  To compensate, the datasource
implementation maintains a pool of open connections.  The `max-pool-size` specifies the maximum number of connections it will pool.
You may want to change the value of this depending on the load of your system.

. Define the database username and password that is needed to connect to the database.  This step is necessary for at least PostgreSQL. You may be concerned that these credentials are in clear text in the example. Methods exist to obfuscate these credentials, but these methods are beyond the scope of this guide.

NOTE:  For more information about datasource features, see link:{appserver_datasource_link}[the datasource configuration chapter] in the _{appserver_admindoc_name}_.
