#!/bin/bash

# Make sure we're not confused by old, incompletely-shutdown httpd
# context after restarting the container.  httpd won't start correctly
# if it thinks it is already running.
rm -rf /opt/jboss/httpd/httpd/logs/httpd.pid

exec /opt/jboss/httpd/sbin/apachectl -D FOREGROUND
