<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="Concepts for multi-cluster deployments (experimental)"
summary="Understand experimental multi-cluster deployment with synchronous replication without an external {jdgserver_name} cluster."
tileVisible="false" >

<#include "/templates/experimental-feature.adoc">

This topic describes a highly available multi-cluster setup and the behavior to expect.
It outlines the requirements of the high availability architecture and describes the benefits and tradeoffs.

== When to use this setup

Use this setup to provide {project_name} deployments that are able to tolerate cluster failures, reducing the likelihood of downtime.

Unlike the standard <@links.ha id="multi-cluster-concepts" />, this setup does not require an external {jdgserver_name} cluster, which simplifies the deployment architecture and removes any requirement for a specific environment.

== Deployment, data storage and caching

Two or more independent {project_name} deployments running in different sites are connected with a low-latency network connection.
Users, realms, clients, sessions, and other entities are stored in a database that is replicated synchronously across all sites.
The realms and other read-intensive data are cached in the {project_name} embedded Infinispan caches as local caches.
When the data is changed in one {project_name} instance, that data is updated in the database, and an invalidation message is sent to the other site using the database.

image::high-availability/active-active-cacheless.dio.svg[]

== Causes of data and service loss

While this setup aims for high availability, the following situations can still lead to service or data loss:

* {project_name} site failure may result in requests failing in the period between the failure and the load balancer detecting it, as requests may still be routed to the failed site.

* Once failures occur in the communication between the sites, manual steps may be necessary depending on the database vendor.

* Degraded setups can lead to service or data loss if additional components fail.
Monitoring is necessary to detect degraded setups.

== Failures which this setup can survive

[%autowidth]
|===
| Failure | Recovery | RPO^1^ | RT^2^

| Database node
| If the writer instance fails, the database can promote a reader instance in the same or other site to be the new writer.
| No data loss
| Seconds to minutes (depending on the database)

| {project_name} node
| Multiple {project_name} instances run in each site.
If one instance fails, some incoming requests might receive an error message or be delayed for some seconds.
| No data loss
| Less than 30 seconds

| Connectivity database
| If the connectivity between sites is lost, the synchronous replication will fail.
Some requests might receive an error message or be delayed for a few seconds.
Manual operations might be necessary depending on the database.
| No data loss^3^
| Seconds to minutes (depending on the database)

| Site failure
| If none of the {project_name} nodes are available, the load balancer will detect the outage and redirect the traffic to the other site.
Some requests might receive an error message until the load balancer detects the failure.
| No data loss^3^
| Less than two minutes

|===

.Table footnotes:
^1^ Tested Recovery Point Objective, assuming all parts of the setup were healthy at the time this occurred. +
^2^ Maximum Recovery Time observed. +
^3^ Manual operations may be needed to restore the degraded setup.

The statement "`No data loss`" depends on the setup not being degraded from previous failures, which includes completing any pending manual operations to resynchronize the state between the sites.

== Known limitations

Site Failure::
A successful failover requires a setup not degraded from previous failures.
All manual operations like a re-synchronization after a previous failure must be complete to prevent data loss.
Use monitoring to ensure degradations are detected and handled in a timely manner.

== Questions and answers

Why synchronous database replication?::
A synchronously replicated database ensures that data written in one site is always available in the other site after site failures and no data is lost.
It also ensures that the next request will not return stale data, independent of which site serves it.

Why is a low-latency network between sites needed?::
Synchronous replication defers the response to the caller until the data is received at the other site.
A low latency is necessary as each request can potentially involve multiple interactions between the sites when data is updated, which would amplify the latency.

Is a synchronous cluster less stable than an asynchronous cluster?::
An asynchronous setup would handle network failures between the sites gracefully, while the synchronous setup would delay requests and throw errors to the caller where the asynchronous setup would have deferred the writes to the database on the other site.
However, as the sites would never be fully up-to-date, this setup could lead to data loss during failures.
This would include:
+
--
* Lost changes leading to users being able to log in with an old password because database changes are not replicated to the other site at the point of failure when using an asynchronous database.
--
+
Therefore, tradeoffs exist between high availability and consistency. The focus of this topic is to prioritize consistency over availability with {project_name}.

</@tmpl.guide>
