<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="Deploying {project_name} for HA with the Operator"
summary="Deploy {project_name} for high availability with the {project_name} Operator as a building block."
tileVisible="false" >

<#include "/templates/experimental-feature.adoc">

This {section} describes advanced {project_name} configurations for {kubernetes} which are load tested and will recover from single Pod failures.

These instructions are intended for use with the setup described in the <@links.ha id="multi-cluster-experimental-concepts"/> {section}.

== Prerequisites

* {kubernetes} cluster running.
* Understanding of a <@links.operator id="basic-deployment" /> of {project_name} with the {project_name} Operator.
* A database deployed with synchronous replication across sites.

== Procedure

. Determine the sizing of the deployment using the <@links.ha id="multi-cluster-concepts-memory-and-cpu-sizing" /> {section}.

. Install the {project_name} Operator as described in the <@links.operator id="installation" /> {section}.

. Secure the database connection by creating a `ConfigMap` with the database certificate bundle:
+
[source,bash]
----
kubectl --namespace keycloak create configmap keycloak-db-rootcert --from-file db-ca.pem=/path/to/certificate.pem
----

. Deploy the {project_name} CR with the following values with the resource requests and limits calculated in the first step:
+
[source,yaml]
----
include::../examples/generated/keycloak-cacheless.yaml[tag=keycloak-cacheless]
----
<1> Set the database URL.
<2> The database connection pool initial, max and min size should be identical to allow statement caching for the database.
Adjust this number to meet the needs of your system.
With the cacheless feature, authentication sessions and action tokens are stored in the database, which increases database load compared to setups with an external {jdgserver_name} cluster. Adjust the pool size accordingly.
See the <@links.ha id="multi-cluster-concepts-database-connections" /> {section} for details.
<3> Specify the URL to your custom {project_name} image. If your image is optimized, set the `startOptimized` flag to `true`.
<4> Enable the `cacheless` feature to remove the requirement for an external {jdgserver_name} cluster.
<5> Set a unique cluster name that identifies this cluster. Each cluster must have a distinct name; no two clusters may share the same name.
<6> To be able to analyze the system under load, enable the metrics endpoint.
<7> Secure the database connection.
<8> Specify the `ConfigMap` name that contains the database certificate bundle.
The Operator will automatically mount the file in directory `/opt/keycloak/conf/truststores/configmap-<config map name>/<file-name>`

<#include "/high-availability/partials/building-blocks/verifying-deployment.adoc" />

<#include "/high-availability/partials/building-blocks/sticky-sessions.adoc" />

</@tmpl.guide>
