<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>
<#import "/templates/profile.adoc" as profile>

<@tmpl.guide
title="Multi-cluster deployments (experimental)"
summary="Connect multiple {project_name} deployments without an external {jdgserver_name} cluster" >

<#include "/templates/experimental-feature.adoc">

{project_name} supports deployments that consist of multiple {project_name} instances that connect to each other using its embedded Infinispan caches.
Load balancers can distribute the load evenly across those instances.
Such setups are intended for transparent networks; see <@links.ha id="single-cluster-introduction" /> for more details.

A multi-cluster setup adds additional components to provide high availability that may be needed for some environments.

Unlike the standard <@links.ha id="multi-cluster-introduction" />, it removes the requirement for an external {jdgserver_name} cluster.
This simplifies the deployment architecture and lifts any requirement for a specific environment such as {kubernetes} or AWS.

== When to use a multi-cluster setup

The multi-cluster deployment capabilities of {project_name} are targeted at use cases that:

* Are constrained to a single region or an equivalent low-latency setup.
* Permit planned outages for maintenance.
* Fit within a defined user and request count.
* Can accept the impact of periodic outages.
* Are deployed in data centers with the required network latency and database configuration.

[#multi-cluster-experimental-tested-configuration]
== Tested Configuration

We regularly test {project_name} with the following configuration:

* Two OpenShift single-AZ clusters, in the same AWS Region
** Provisioned with https://www.redhat.com/en/technologies/cloud-computing/openshift/aws[Red Hat OpenShift Service on AWS] (ROSA),
using ROSA HCP.
** All worker nodes reside in a single Availability Zone.
** OpenShift version 4.21.

* Amazon Aurora PostgreSQL database
** High availability with a primary DB instance in one availability zone, and a synchronously replicated reader in the second availability zone.
** Version ${properties["aurora-postgresql.version"]}

* AWS Global Accelerator, sending traffic to both ROSA clusters


[#multi-cluster-experimental-supported-configuration]
== Supported Configuration

The following configurations are supported:

* Two or more clusters with a low-latency network between them.

* A highly available database with synchronous replication.

* An external load balancer to balance requests between the clusters.

<#include "/high-availability/partials/configuration-disclaimer.adoc" />

[#multi-cluster-experimental-load]
<#include "/high-availability/partials/tested-load.adoc" />

<@profile.ifCommunity>
While we did not see a hard limit in our tests with these values, we ask you to test for higher volumes with horizontally and vertically scaled {project_name} instances and databases.
</@profile.ifCommunity>

[#multi-cluster-experimental-limitations]
== Limitations

* During certain failure scenarios, there may be downtime of up to 5 minutes.
* After certain failure scenarios, manual intervention may be required depending on the database vendor.
* During certain switchover scenarios, there may be downtime of up to 5 minutes.

== Next steps

The different {sections} introduce the necessary concepts and building blocks.
For each building block, a blueprint shows how to set up a fully functional example.
Additional performance tuning and security hardening are still recommended when preparing a production setup.

<@profile.ifCommunity>

== Concept and building block overview

* <@links.ha id="multi-cluster-experimental-concepts" />

== Blueprints for building blocks

* <@links.ha id="multi-cluster-experimental-deploy-keycloak-kubernetes" />

//
// == Operational procedures

</@profile.ifCommunity>

</@tmpl.guide>
