
[id="installing-client-adapter_{context}"]
= Installing the {appserver_name} client adapter

When {appserver_name} and {project_name} are installed on the same machine, {appserver_name} requires some modification. To make this modification, you install a {project_name} client adapter.

.Prerequisites

* {appserver_name} is installed.

* You have a backup of the `../standalone/configuration/standalone.xml` file if you have customized this file.

.Procedure
ifeval::[{project_community}==true]
. Download the *WildFly OpenID Connect Client Adapter* distribution from link:https://www.keycloak.org/downloads.html[keycloak.org].
endif::[]

ifeval::[{project_product}==true]
. Download the *Client Adapter for EAP 7* from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=core.service.rhsso[Red Hat customer portal].
endif::[]

. Change to the root directory of {appserver_name}.

. Unzip the downloaded client adapter in this directory.  For example:
+
[source,bash,subs=+attributes]
----
$ unzip <filename>.zip
----

. Change to the bin directory.
+
[source,bash,subs=+attributes]
----
$ cd bin
----

. Run the appropriate script for your platform.
+
[NOTE]
====
If you receive a `file not found`, make sure that you used `unzip` in the previous step.  This method of extraction installs the files in the right place.
====

ifeval::[{project_product}==true]
+
.Linux/Unix
[source,bash,subs=+attributes]
----
$ ./jboss-cli.sh --file=adapter-elytron-install-offline.cli
----

+
.Windows
[source,bash,subs=+attributes]
----
> jboss-cli.bat --file=adapter-elytron-install-offline.cli
----
endif::[]

ifeval::[{project_community}==true]
+
.WildFly 10 on Linux/Unix
[source,bash,subs=+attributes]
----
$ ./jboss-cli.sh --file=adapter-install-offline.cli
----

+
.WildFly 10 on Windows
[source,bash,subs=+attributes]
----
> jboss-cli.bat --file=adapter-install-offline.cli
----

+
.Wildfly 11 on Linux/Unix
[source,bash,subs=+attributes]
----
$ ./jboss-cli.sh --file=adapter-elytron-install-offline.cli
----

+
.Wildfly 11 on Windows
[source,bash,subs=+attributes]
----
> jboss-cli.bat --file=adapter-elytron-install-offline.cli
----
endif::[]

+
[NOTE]
====
This script makes the necessary edits to the `.../standalone/configuration/standalone.xml` file. 
====

. Start the application server.

+
.Linux/Unix
[source,bash,subs=+attributes]
----
$ ./standalone.sh
----

+
.Windows
[source,bash,subs=+attributes]
----
> ...\standalone.bat
----
