
[id="adjusting-ports_{context}"]
= Adjusting the port used by {project_name}

The instructions in this guide apply to running {appserver_name} on the same machine as the {project_name} server. In this situation, even though {appserver_name} is bundled with {project_name}, you cannot use {appserver_name} as an application container. You must run a separate {appserver_name} instance for your servlet application.

To avoid port conflicts, you need different ports to run {project_name} and {appserver_name}.

.Prerequisites

* You have an admin account for the admin console.
* You created a demo realm.
* You created a user in the demo realm.

.Procedure

ifeval::[{project_community}==true]
. Download WildFly from link:https://www.wildfly.org/[WildFly.org].
endif::[]
ifeval::[{project_product}==true]
. Download JBoss EAP 7.3 from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?product=appplatform&downloadType=distributions[Red Hat customer portal].
endif::[]

. Unzip the downloaded {appserver_name}.
+
[source,bash,subs=+attributes]
----
$ unzip <filename>.zip
----

. Change to the {project_name} root directory.

. Start the {project_name} server by supplying a value for the `jboss.socket.binding.port-offset` system property. This value is added to the base value of every port opened by the {project_name} server. In this example, *100* is the value.

+
.Linux/Unix
[source,bash,subs=+attributes]
----
$ cd bin
$ ./standalone.sh -Djboss.socket.binding.port-offset=100
----

+
.Windows
[source,bash,subs=+attributes]
----
> ...\bin\standalone.bat -Djboss.socket.binding.port-offset=100
----

. Confirm that the {project_name} server is running. Go to http://localhost:8180/auth/admin/ .
+
If the admin console opens, you are ready to install a client adapter that enables {appserver_name} to work with {project_name}.
