{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    {{ include "keycloak.selectorLabels" . | indent 4 }}
  type: ClusterIP
{{- end }}
