[[_docker_compose_yaml]]

=== Docker Compose YAML File

WARNING: This installation method is meant to be an easy way to get a docker registry authenticating against a keycloak server.  It is intended for development purposes only and should never be used in a production or production-like environment.

The zip file installation mechanism provides a quickstart for developers who want to understand how the keycloak server can interact with the docker registry.  In order to configure:

 1. From the desired realm, create a client configuration.  At this point you won't have a docker registry - the quickstart will take care of that part.
 1. Choose the "Docker Compose YAML" option from the installation tab and download the .zip file
 1. Unzip the archive to the desired location, and open the directory.
 1. Start the docker registry with `docker-compose up`

INFO: it is recommended that you configure the docker registry client in a realm other than 'master', since the HTTP Basic auth flow will not present forms.

Once the above configuration has taken place, and the keycloak server and docker registry are running, docker authentication should be successful:

	[user ~]# docker login localhost:5000 -u $username
	Password: *******
	Login Succeeded

