== Breaking changes

Breaking changes are identified as requiring changes from existing users to their configurations.

=== Changes to port behaviour with the `X-Forwarded-Host` header

The `X-Forwarded-Host` header can optionally also contain the port. In previous versions when the port was omitted from the header,
{project_name} fell back to the actual request port. For example if {project_name} was listening on port 8080 and the request contained
`X-Forwarded-Host: example.com` header, the resolved URL was `+http://example.com:8080+`.

This is now changed and omitting the port results in removing it from the resolved URL. The resolved URL from the previous example
would now be `http://example.com`.

To mitigate that, either make your reverse proxy include the port in the `X-Forwarded-Host` header or configure it to set
the `X-Forwarded-Port` header with the desired port.

= Removal of XSS Header

We have removed the X-XSS-Protection response header from Keycloak, this header was a feature of Internet Explorer,
Chrome and Safari that stopped pages from loading when they detected reflected cross-site scripting (XSS) attacks.

Since, this header is no longer supported in any of the user agents supported by Keycloak and has been replaced by
Content-Security-Policy. More details about the header can be found https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection[here]
