== Breaking changes

Breaking changes are identified as requiring changes from existing users to their configurations.
In minor or patch releases we will only do breaking changes to fix bugs.

=== <TODO>

== Notable changes

Notable changes where an internal behavior changed to prevent common misconfigurations, fix bugs or simplify running {project_name}.

=== Usage of the `exact` request parameter when searching users by attributes

If you are querying users by attributes through the User API where you want to fetch users that match a specific attribute key (regardless the value),
you should consider setting the `exact` request parameter to `false` when invoking the `/admin/realms/{realm}/users` using
the `GET` method.

For instance, searching for all users with the attribute `myattribute` set should be done as follows:

```
GET /admin/realms/{realm}/users?exact=false&q=myattribute:
```

The {project_name} Admin Client is also updated with a new method to search users by attribute using the `exact` request parameter.

== Deprecated features

The following sections provide details on deprecated features.

=== <TODO>

== Removed features

The following features have been removed from this release.

=== <TODO>
