////

== Breaking changes

Breaking changes are identified as requiring changes from existing users to their configurations.

////

== Notable changes

Notable changes where an internal behavior changed to prevent common misconfigurations, fix bugs or simplify running {project_name}.

=== Upgrade procedure changed for the distribution

If you are upgrading {project_name} by downloading the distribution, the upgrade procedure has been changed. Previously it recommended copying over the contents from the `conf/` folder from the old to the new installation.
The new procedure recommends to re-apply any changes to `cache-ispn.xml` or a custom cache configuration based on the file included in the new version.

This prevents accidentally downgrading functionality, for example, by using an old `cache-ispn.xml` file from a previous version.

=== Problematic cache configurations ignored

Previous versions {project_name} warned about problematic configurations, for example, if a wrong number of owners was configured or a cache size was set when it should not have been set when enabling volatile user sessions.
The current version will still warn about those settings, but will also ignore them to ensure a correct behavior and to avoid data loss.

=== Volatile Session Cache Defaults

If the `persistent-user-sessions` feature is disabled, i.e. volatile sessions are configured, {project_name} now prevents
`num_owners=1` being configured unless a shared persistent store is also configured. This is to prevent data loss on cache
rebalances.
