// ------------------------ Breaking changes ------------------------  //
== Breaking changes

Breaking changes are identified as those that might require changes for existing users to their configurations or applications.
In minor or patch releases, {project_name} will only introduce breaking changes to fix bugs.

=== Stricter access control for managing permission tickets

In order to improve security, the access control for managing permission tickets has been made stricter where
only users (or service accounts) granted with the `uma-protection` role can manage permission tickets for a given
resource server. The only exception is the resource server itself, which can manage its permission tickets without the `uma-protection` role.

=== Stricter access control for fetching user profile configuration and metadata

In order to improve security, the access control for fetching user profile configuration and metadata from a realm has been made stricter,
and it is no longer possible to fetch this information if the administrator is granted with any administrative role.

Instead, the administrator must have explicit permissions to view or manage users, or by
having the `view-realm`, or `manage-realm`, or `view-users`, or `manage-users`, or `query-users` roles.
