== Breaking changes

Breaking changes are identified as requiring changes from existing users to their configurations.

=== Changes to port behaviour with the `X-Forwarded-Host` header

The `X-Forwarded-Host` header can optionally also contain the port. In previous versions when the port was omitted from the header,
{project_name} fell back to the actual request port. For example if {project_name} was listening on port 8080 and the request contained
`X-Forwarded-Host: example.com` header, the resolved URL was `+http://example.com:8080+`.

This is now changed and omitting the port results in removing it from the resolved URL. The resolved URL from the previous example
would now be `http://example.com`.

To mitigate that, either make your reverse proxy include the port in the `X-Forwarded-Host` header or configure it to set
the `X-Forwarded-Port` header with the desired port.

=== Changes to installing Oracle JDBC driver

The required JAR for the Oracle JDBC driver that needs to be explicitly added to the distribution has changed.
Instead of providing `ojdbc11` JAR, use `ojdbc17` JAR as stated in the https://www.keycloak.org/server/db#_installing_the_oracle_database_driver[Installing the Oracle Database driver] guide.

== Notable changes

Notable changes where an internal behavior changed to prevent common misconfigurations, fix bugs or simplify running {project_name}.

=== LDAP provider now can store new users/groups in a sub-DN of the base DN

When adding new users and groups, the LDAP provider would always store them in the same DN configured for the searches. But in some deployments, admins want to configure a broader DN with `subtree` scope to fetch users from multiple sub-DNs, but they don't want new users or groups to be stored in this base DN in LDAP. Instead, they would like to chose one of the sub-DNs for that.

It is now possible to control where new users/groups will be created using the new `Relative User Creation DN` config option in the LDAP provider and also in the LDAP group mapper. For more details, check the link:{adminguide_link}#_ldap[LDAP admin guide]
