== Breaking changes

Breaking changes are identified as those that might require changes for existing users to their configurations or applications.
In minor or patch releases, {project_name} will only introduce breaking changes to fix bugs.

=== Stricter access control for managing permission tickets

In order to improve security, the access control for managing permission tickets has been made stricter where
only users (or service accounts) granted with the `uma-protection` role can manage permission tickets for a given
resource server. The only exception is the resource server itself, which can manage its permission tickets without the `uma-protection` role.

=== Stricter access control for listing realm and client roles

In order to improve security, the access control for listing realm and client roles has been made stricter, and granting
only the `query-*` role to an administrator is no longer sufficient to list roles.

Instead, the administrator must have explicit permissions to view or manage the realm or client for which they want to list roles, or by
having the `view-realm` or `manage-realm` role for realm roles, or `view-clients` or `manage-clients` role for client roles.

// ------------------------ Notable changes ------------------------ //
////
== Notable changes

Notable changes may include internal behavior changes that prevent common misconfigurations, bugs that are fixed, or changes to simplify running {project_name}.

=== <TODO>
////

// ------------------------ Deprecated features ------------------------ //
////
== Deprecated features

The following sections provide details on deprecated features.

=== <TODO>
////

// ------------------------ Removed features ------------------------ //
////
== Removed features

The following features have been removed from this release.

=== <TODO>
////
