// ------------------------ Notable changes ------------------------ //
== Notable changes

Notable changes where an internal behavior changed to prevent common misconfigurations, fix bugs or simplify running {project_name}.

=== User sessions created with "Remember Me" are no longer valid if "Remember Me" is disabled for the realm

When the "Remember Me" option is disabled in the realm settings, all user sessions previously created with the "Remember Me" flag are now considered invalid.
Users will be required to log in again, and any associated refresh tokens will no longer be usable.
User sessions created without selecting "Remember Me" are not affected.

=== Added database indexes on `OFFLINE_CLIENT_SESSION` table

This adds new indexes on `OFFLINE_CLIENT_SESSION` table to improve performance when retrieving or deleting client sessions.

If those tables contain more than 300000 entries, {project_name} will skip the index creation by default during the automatic schema migration and instead log the SQL statement on the console during migration to be applied manually after {project_name}'s startup.
See the link:{upgradingguide_link}[{upgradingguide_name}] for details on how to configure a different limit.


=== Accepting only normalized paths in requests

{project_name} accepts HTTP requests with paths containing double dots (`..`) or double slashes (`//`). When processing them, it normalized the path by collapsing double slashes and normalized the path according to RFC3986.
As this has led to a hard-to-configure URL filtering, for example, in reverse proxies, the normalization can now be disabled, and {project_name} then responds with an HTTP 400 response code.

To reject non-normalized URLs, set the option `http-accept-non-normalized-paths` to `false`.
To analyze rejected requests in the server log, enable debug logging for `org.keycloak.quarkus.runtime.services.RejectNonNormalizedPathFilter`.

In future versions, {project_name} will reject non-normalized URLs be enabled by default and accepting non-normalized paths will be deprecated.
Due to that, we encourage users to enable this option while paying attention to client configurations and logs for errors due to misconfigured clients and calls with non-normalized URLs.
