package org.keycloak.protocol.oidc.refresh;

import org.keycloak.OAuthErrorException;
import org.keycloak.protocol.oidc.TokenManager;
import org.keycloak.provider.Provider;
import org.keycloak.representations.RefreshToken;

/**
 * Provider responsible for verification of refresh tokens and issuing of new refresh tokens
 */
public interface RefreshTokenProvider extends Provider {

    /**
     * Method is triggered during initial issuance of refresh token - usually after successful user authentication.
     *
     * @param initialRefreshTokenCtx context information with the data useful to determine if this provider can be used to generate refresh token
     * @return true if this provider can be used to generate refresh token. In this case method {@link #generateRefreshToken(InitialRefreshTokenContext)} would be used
     * for this provider to generate new refresh token. Keycloak iterates over available providers to determine which one can be used.
     * Providers are sorted by their priority (based on the "order" of particular ProviderFactory)
     */
    boolean supports(InitialRefreshTokenContext initialRefreshTokenCtx);

    /**
     * Method is triggered during initial issuance of refresh token - usually after successful user authentication.
     * Refresh token is generated by single provider, which was first available provider returned by method {@link #supports(InitialRefreshTokenContext)}
     *
     * @param initialRefreshTokenCtx context information with the data useful to determine
     * @return newly generated refresh token
     * @throws RefreshTokenException in case of some issues during refresh token generation
     */
    RefreshToken generateRefreshToken(InitialRefreshTokenContext initialRefreshTokenCtx) throws RefreshTokenException;

    /**
     * Invoked during refresh-token request.
     *
     * @param ctx Context, which contains old refresh token and some other data
     * @return True if this provider supports verification of the refresh token from the context
     */
    boolean supports(RefreshTokenContext ctx);

    /**
     * Invoked during refresh-token request. Implements verifications related to old refresh token and creates token-response if all the verifications are successful
     *
     * @param ctx Context, which contains old refresh token and some other data
     * @return successful token-response with new tokens and data, which would be returned in the successful token response
     * @throws OAuthErrorException In case that validation failed or some other issue happened during token refresh
     */
    TokenManager.AccessTokenResponseBuilder refreshAccessToken(RefreshTokenContext ctx) throws OAuthErrorException;

    @Override
    default void close() {
    }

}
