parent=base
import=common/keycloak
deprecatedMode=false
darkMode=true

description=Account UI built with Lit and PatternFly 6 Web Components

favIcon=/favicon.svg
favIconType=image/svg+xml

kcDarkModeClass=pf-v6-theme-dark

meta=viewport==width=device-width,initial-scale=1
