// Module included in the following assemblies:
//
// server_admin/topics/users.adoc

[id="con-required-actions_{context}"]
= Required Actions

You can set the actions that a user must perform at the first login. These actions are required after the user provides credentials. After the first login, these actions are no longer required. You add required actions on the *Details* tab of that user.

The following are examples of required action types:

Update Password:: 
   The user must change their password.

Configure OTP::
   The user must configure a one-time password generator on their mobile device using either the Free OTP or Google Authenticator application.

Verify Email::
   The user must verify their email account. An email will be sent to the user with a validation link that they must click. Once this workflow is successfully completed, the user will be allowed to log in.

Update Profile::
   The user must update profile information, such as name, address, email, and phone number.


include::proc-setting-required-actions.adoc[leveloffset=3]
include::proc-setting-default-required-actions.adoc[leveloffset=3]
include::proc-enabling-terms-conditions.adoc[leveloffset=3]
