[id="proc-setting-password-user_{context}"]
= Setting a password for a user

[role="_abstract"]
If a user does not have a password, or if the password has been deleted, the *Set Password* section is displayed.
If a user already has a password, it can be reset in the *Reset Password* section.

.Procedure
. Type in a new password, in the *Set Password* section.
. Click *Set Password*.
+
NOTE: If the *Temporary* radion button is set to *ON*, the password is temporary and the user must change the password after the first login. If a user prefers to create a password that is persistent, the *Temporary* radio button must be set to *OFF* and the user must click *Set Password*.
+
. Alternatively, you can send an email to the user that requests the user reset the password.  
.. Navigate to the *Reset Actions* list.
.. Click *Update Password* from the list.
.. Click *Send Email*. The sent email contains a link that directs the user to the *Update Password* window.
.. Optionally, you can set the validity of the email link. This is set to the default preset in the *Tokens* tab in the realm setiings.
