// Module included in the following assemblies:
//
// server_admin/topics/users.adoc

[id="proc-setting-password-user_{context}"]
= Setting a password for a user

[role="_abstract"]
If a user does not have a password, or if the password has been deleted, the *Set Password* section is displayed.

If a user already has a password, it can be reset in the *Reset Password* section.

.Procedure
. Click *Users* in the menu. The *Users* page is displayed.
. Select a user.
. Click the *Credentials* tab.
. Type a new password in the *Set Password* section.
. Click *Set Password*.
+
NOTE: If *Temporary* is *ON*, the user must change the password at the first login. To allow users to keep the password supplied, set *Temporary* to *OFF.*  The user must click *Set Password* to change the password.
+
. Alternatively, you can send an email to the user that requests the user reset the password.  
.. Navigate to the *Reset Actions* list under *Credential Reset*.
.. Select *Update Password* from the list.
.. Click *Send Email*. The sent email contains a link that directs the user to the *Update Password* window.
.. Optionally, you can set the validity of the email link. This is set to the default preset in the *Tokens* tab in *Realm Settings*.
