[[_kerberos]]
= Kerberos brokering

Keycloak supports login with Kerberos ticket through SPNEGO.
SPNEGO (Simple and Protected GSSAPI Negotiation Mechanism) is used to authenticate transparently through the web browser after the user has been authenticated when logging-in his session.
For non-web cases or when ticket is not available during login, Keycloak also supports login with Kerberos username/password. 

A typical use case for web authentication is the following: 

. User logs into his desktop (Such as a Windows machine in Active Directory domain or Linux machine with Kerberos integration enabled). 
. User then uses his browser (IE/Firefox/Chrome) to access a web application secured by Keycloak. 
. Application redirects to Keycloak login. 
. Keycloak sends HTML login screen together with status 401 and HTTP header `WWW-Authenticate: Negotiate`                
. In case that browser has Kerberos ticket from desktop login, it transfers the desktop sign on information to the Keycloak in header `Authorization: Negotiate 'spnego-token'` . Otherwise it just displays login screen. 
. Keycloak validates token from browser and authenticate user.
  It provisions user data from LDAP (in case of LDAPFederationProvider with Kerberos authentication support) or let user to update his profile and prefill data (in case of KerberosFederationProvider). 
. Keycloak returns back to the application.
  Communication between Keycloak and application happens through OpenID Connect or SAML messages.
  The fact that Keycloak was authenticated through Kerberos is hidden from the application.
  So Keycloak acts as broker to Kerberos/SPNEGO login.     

For setup there are 3 main parts: 

. Setup and configuration of Kerberos server (KDC) 
. Setup and configuration of Keycloak server 
. Setup and configuration of client machines     

== Setup of Kerberos server

This is platform dependent.
Exact steps depend on your OS and the Kerberos vendor you're going to use.
Consult Windows Active Directory, MIT Kerberos and your OS documentation for how exactly to setup and configure Kerberos server. 

At least you will need to: 

* Add some user principals to your Kerberos database.
  You can also integrate your Kerberos with LDAP, which means that user accounts will be provisioned from LDAP server. 
* Add service principal for "HTTP" service.
  For example if your Keycloak server will be running on `www.mydomain.org` you may need to add principal `HTTP/www.mydomain.org@MYDOMAIN.ORG`                        assuming that MYDOMAIN.ORG will be your Kerberos realm. 
+
For example on MIT Kerberos you can run "kadmin" session.
If you are on same machine where is MIT Kerberos, you can simply use command: 

[source]
----
sudo kadmin.local
----                        
Then add HTTP principal and export his key to keytab file with the commands like: 

[source]
----

addprinc -randkey HTTP/www.mydomain.org@MYDOMAIN.ORG
ktadd -k /tmp/http.keytab HTTP/www.mydomain.org@MYDOMAIN.ORG
----                        

Keytab file `/tmp/http.keytab` will need to be accessible on the host where keycloak server will be running. 
        
== Setup and configuration of Keycloak server

* Install kerberos client.
  This is again platform dependent.
  If you are on Fedora, Ubuntu or RHEL, you can install package `freeipa-client`, which contains Kerberos client and bunch of other stuff. 
Configure kerberos client (on linux it's in file `/etc/krb5.conf` ). You need to put your Kerberos realm and at least configure the Http domains your server will be running on.
For the example realm MYDOMAIN.ORG you may configure `domain_realm` section like this: 

[source]
----
[domain_realm]
  .mydomain.org = MYDOMAIN.ORG
  mydomain.org = MYDOMAIN.ORG
----             
   
* Export keytab file with HTTP principal and make sure the file is accessible to the process under which Keycloak server is running.
  ** For production, it's ideal if it's readable just by this process and not by someone else.
  ** For MIT Kerberos example above, we already exported keytab to `/tmp/http.keytab` . If your KDC and Keycloak are running on same host, you have file already available. 
* Run Keycloak server and configure SPNEGO/Kerberos authentication in Keycloak admin console.
Keycloak supports Kerberos authentication through <<_user_federation,Federation provider SPI>> . We have 2 federation providers with Kerberos authentication support: 

Kerberos::
  This provider is useful if you want to authenticate with Kerberos `NOT` backed by LDAP server.
  In this case, users are usually created to Keycloak database after first successful SPNEGO/Kerberos login and they may need to update profile after first login, as Kerberos protocol itself doesn't provision any data like first name, last name or email. 

LDAP::
  This provider is useful if you want to authenticate with Kerberos backed by LDAP server.
* In this case, data about users are provisioned from LDAP server after successful Kerberos authentication.                 
* Finally you may need to check the Kerberos authenticator correctly configured.
  You can go to `Authentication` tab in admin console and select `Browser` flow.
  Here you will see `Kerberos` authenticator, which is used by Keycloak for SPNEGO handshake with client (exchange `Negotiate` header etc.). By default it's disabled, so Keycloak doesn't ask for Negotiate header, however once you configured federation provider in previous step, it's automatically switched to `ALTERNATIVE`.
  So defacto you don't need to do anything, just check that it's really switched to Alternative. 
+
Alternative means that Keycloak tries to ask browser for Negotiate header, but if it's not available, it will continue on next authenticator (which usually means displaying username/password form to user). You can switch to `REQUIRED` if you want to enforce login with kerberos ticket and not allow fallback to username/password form. 


== Setup and configuration of client machines

Clients need to install kerberos client and setup krb5.conf as described above.
Additionally they need to enable SPNEGO login support in their browser.
See for example http://www.microhowto.info/howto/configure_firefox_to_authenticate_using_spnego_and_kerberos.html[this]   for more info about Firefox.
URI `.mydomain.org` must be allowed in `network.negotiate-auth.trusted-uris` config option. 

In windows domain, clients usually don't need to configure anything special as IE is already able to participate in SPNEGO authentication for the windows domain. 

== Example setups

For easier testing with Kerberos, we provided some example setups to test. 

=== Keycloak and FreeIPA docker image

Once you install https://www.docker.com/[docker], you can run docker image with http://www.freeipa.org/[FreeIPA]         server installed.
FreeIPA provides integrated security solution with MIT Kerberos and 389 LDAP server among other things . The image provides also Keycloak server configured with LDAP Federation provider and enabled SPNEGO/Kerberos authentication against the FreeIPA server.
See details https://github.com/mposolda/keycloak-freeipa-docker/blob/master/README.md[here] . 

=== ApacheDS testing Kerberos server

For quick testing and unit tests, we use very simple http://directory.apache.org/apacheds/[ApacheDS] Kerberos server.
You need to build Keycloak from sources and then run Kerberos server with maven-exec-plugin from our testsuite.
See details https://github.com/keycloak/keycloak/blob/master/misc/Testsuite.md#kerberos-server[here] . 

== Credential delegation

One scenario supported by Kerberos 5 is credential delegation.
In this case when user receives forwardable TGT and authenticates to the web server, then web server might be able to reuse the ticket and forward it to another service secured by Kerberos (for example LDAP server or IMAP server). 

The scenario is supported by Keycloak, but there is tricky thing that SPNEGO authentication is done by Keycloak server but GSS credential will need to be used by your application.
So you need to enable built-in `gss delegation credential` protocol mapper in admin console for your application.
This will cause that Keycloak will deserialize GSS credential and transmit it to the application in access token.
Application will need to deserialize it and use it for further GSS calls against other services.
We have an example, which is showing it in details.
It's in `examples/kerberos` in the Keycloak example distribution or demo distribution download.
You can also check the example sources directly https://github.com/keycloak/keycloak/blob/master/examples/kerberos[here] . 

Once you deserialize the credential from the access token to the GSSCredential object, then GSSContext will need to be created with this credential passed to the method `GSSManager.createContext` for example like this: 

[source]
----
GSSContext context = gssManager.createContext(serviceName, krb5Oid,
    deserializedGssCredFromKeycloakAccessToken, GSSContext.DEFAULT_LIFETIME);
----        

Note that you also need to configure `forwardable` kerberos tickets in `krb5.conf` file and add support for delegated credentials to your browser.
For details, see the kerberos example from Keycloak examples set as mentioned above. 

WARNING: Credential delegation has some security implications.
So enable the protocol claim and support in browser just if you really need it.
It's highly recommended to use it together with HTTPS.
See for example http://www.microhowto.info/howto/configure_firefox_to_authenticate_using_spnego_and_kerberos.html#idp27072[this article]                for details. 

== Troubleshooting

If you have issues, we recommend to enable more logging by: 

* Enable `Debug` flag in admin console for Kerberos or LDAP federation providers 
* Enable TRACE logging for category `org.keycloak` in logging section of `$WILDFLY_HOME/standalone/configuration/standalone.xml` to receive more info `$WILDFLY_HOME/standalone/log/server.log`                    
* Add system properties `-Dsun.security.krb5.debug=true` and `-Dsun.security.spnego.debug=true`                            
