
[[_social_config]]
= Social Login Config

To enable log in with a social network you need to enable social login for your realm and configure one or more social providers. 

== Enable social login

To configure social login, open the `Keycloak Admin Console`, select your realm from the drop-down box in the top left corner.
In the `Login Options` section click on `Social login` to set it to `ON`.
Click save settings, then click on `Social` in the menu at the top. 

To enable a social provider select the provider you want from the drop-down and click on `Add Provider`.
Then continue to the section below that provides specific instructions for the provider you are adding. 

== Social-only login

It's possible to configure a realm to only allow social login.
To do this open the `Keycloak Admin Console`, select your realm from the drop-down box in the top left corner.
Click the `Credentials` tab, and click on the `x` next to `password` in the `Required User Credentials`.
This will disable login with username and password. 

[[_social_callbackurl]]
== Social Callback URL

There is a single callback url used by all realms and social providers.
This makes it possible to share the configuration for a social network between multiple realms.
An example callback url is `http://localhost:8080/auth/rest/social/callback`.
To get the callback url for your server replace `http://localhost:8080` with the base address of your server.
You can also find the callback url in the Keycloak Admin Console under social settings. 