
===== IDP Element

Everything in the IDP element describes the settings for the IDP the SP is communicating with. 

[source,xml]
----
<IDP entityID="idp"
     signaturesRequired="true"
     signatureAlgorithm="RSA_SHA1"
     signatureCanonicalizationMethod="http://www.w3.org/2001/10/xml-exc-c14n#">
...
</IDP>
----
entityID::
  This is the issuer ID of the IDP. _REQUIRED._. 

signaturesRequired::
  If set to true, the client adapter will sign every document it sends to the IDP.
  Also, the client will expect that the IDP will be signing an documents sent to it.
  This switch sets the default for all request and response types, but you will see later that you have some fine grain control over this. _OPTIONAL._                        

signatureAlgorithm::
  This is the signature algorithm that the IDP expects signed documents to use _OPTIONAL._.
  The default value is RSA_SHA256, but you can also use RSA_SHA1, RSA_256, RSA_512, and DSA_SHA1. 

signatureCanonicalizationMethod::
  This is the signature canonicalization method that the IDP expects signed documents to use _OPTIONAL._.
  The default value is `http://www.w3.org/2001/10/xml-exc-c14n#` and should be good for most IDPs.         

