<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>
<#import "/templates/profile.adoc" as profile>

<@tmpl.guide
title="Multi-cluster deployments (v2)"
summary="Connect multiple {project_name} deployments without an external {jdgserver_name} cluster" >

<#include "/templates/experimental-feature.adoc">

{project_name} allows deployments that consist of multiple {project_name} instances that connect to each other using its embedded Infinispan caches.
Load balancers can distribute the load evenly across those instances.
Such setups are intended for transparent networks; see <@links.ha id="single-cluster-introduction" /> for more details.

A multi-cluster setup adds additional components to provide high availability that may be needed for some environments.

Unlike the standard <@links.ha id="multi-cluster-introduction" />, it removes the requirement for an external {jdgserver_name} cluster.
This simplifies the deployment architecture and lifts any requirement for a specific environment such as {kubernetes} or AWS.

== When to use a multi-cluster setup

The multi-cluster deployment capabilities of {project_name} are targeted at use cases that:

* Are constrained to a single region or an equivalent low-latency setup.
* Permit planned outages for maintenance.
* Fit within a defined user and request count.
* Can accept the impact of periodic outages.
* Provide data centers with the appropriate network latency and database configuration.


// TODO: Add an automated test, or remove
////
<#--

[#multi-cluster-v2-tested-configuration]
== Tested Configuration

We regularly test {project_name} with the following configuration:

* Two OpenShift single-AZ clusters, in the same AWS Region
** Provisioned with https://www.redhat.com/en/technologies/cloud-computing/openshift/aws[Red Hat OpenShift Service on AWS] (ROSA),
using ROSA HCP.
** All worker nodes reside in a single Availability Zone.
** OpenShift version 4.21.

* Amazon Aurora PostgreSQL database
** High availability with a primary DB instance in one availability zone, and a synchronously replicated reader in the second availability zone.
** Version ${properties["aurora-postgresql.version"]}

* AWS Global Accelerator, sending traffic to both ROSA clusters
-->
////

[#multi-cluster-v2-infrastructure-requirements]
== Infrastructure requirements

The following infrastructure requirements need to be met:

* A highly available database with synchronous replication.

* Two or more clusters with low latency for read, write, and commit operations to the database.
A latency of less than 5 ms is suggested, and below 10 ms is required.

* A round-trip latency below 5 ms is suggested, and below 10 ms is required, within each cluster.

* An external load balancer to balance requests between the clusters.

Latency and latency spikes amplify in the response time of the service and can lead to queued requests, timeouts, and failed requests.
Networking problems can cause downtimes until the failure detection isolates problematic nodes.

<#include "/high-availability/partials/configuration-disclaimer.adoc" />

////
<#--
// TODO: Add an automated test, or remove
[#multi-cluster-v2-load]
<#include "/high-availability/partials/tested-load.adoc" />

<@profile.ifCommunity>
While we did not see a hard limit in our tests with these values, we ask you to test for higher volumes with horizontally and vertically scaled {project_name} instances and databases.
</@profile.ifCommunity>
-->
////

[#multi-cluster-v2-limitations]
== Limitations

* During certain failure scenarios, there may be downtime of several minutes depending on the configuration of the database, the load balancer, or {project_name}. By default, {project_name} detects the failure of another node within one minute and either isolates it from the cluster or propagates its state via readiness probes to the load balancer.
* After certain failure scenarios, manual intervention may be required depending on the database vendor.

== Next steps

The different {sections} introduce the necessary concepts and building blocks.
For each building block, a blueprint shows how to set up a fully functional example.
Additional performance tuning and security hardening are still recommended when preparing a production setup.

<@profile.ifCommunity>

== Concept and building block overview

* <@links.ha id="multi-cluster-v2-concepts" />

== Example blueprint

While this blueprint uses {kubernetes}, the concepts are not limited to {kubernetes}.

* <@links.ha id="multi-cluster-v2-deploy-keycloak-kubernetes" />

== Operational procedures

* <@links.ha id="multi-cluster-v2-upgrades" />

</@profile.ifCommunity>

</@tmpl.guide>
