package org.keycloak.events;

/**
 * @author <a href="mailto:sthorger@redhat.com">Stian Thorgersen</a>
 */
public enum EventType {

    LOGIN,
    LOGIN_ERROR,
    REGISTER,
    REGISTER_ERROR,
    LOGOUT,
    LOGOUT_ERROR,
    CODE_TO_TOKEN,
    CODE_TO_TOKEN_ERROR,
    REFRESH_TOKEN,
    VALIDATE_ACCESS_TOKEN,
    VALIDATE_ACCESS_TOKEN_ERROR,
    REFRESH_TOKEN_ERROR,
    SOCIAL_LINK,
    SOCIAL_LINK_ERROR,
    REMOVE_FEDERATED_IDENTITY,
    REMOVE_SOCIAL_LINK_ERROR,

    UPDATE_EMAIL,
    UPDATE_EMAIL_ERROR,
    UPDATE_PROFILE,
    UPDATE_PROFILE_ERROR,
    UPDATE_PASSWORD,
    UPDATE_PASSWORD_ERROR,
    UPDATE_TOTP,
    UPDATE_TOTP_ERROR,
    VERIFY_EMAIL,
    VERIFY_EMAIL_ERROR,

    REMOVE_TOTP,
    REMOVE_TOTP_ERROR,

    SEND_VERIFY_EMAIL,
    SEND_VERIFY_EMAIL_ERROR,
    SEND_RESET_PASSWORD,
    SEND_RESET_PASSWORD_ERROR,
    RESET_PASSWORD,
    RESET_PASSWORD_ERROR,

    INVALID_SIGNATURE_ERROR,
    REGISTER_NODE,
    UNREGISTER_NODE,

    USER_INFO_REQUEST,
    USER_INFO_REQUEST_ERROR,

    IDENTITY_PROVIDER_LOGIN,
    IDENTITY_PROVIDER_LOGIN_ERROR,
    IDENTITY_PROVIDER_RESPONSE,
    IDENTITY_PROVIDER_RESPONSE_ERROR,
    IDENTITY_PROVIDER_RETRIEVE_TOKEN,
    IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR,
    IDENTITY_PROVIDER_ACCCOUNT_LINKING,
    IDENTITY_PROVIDER_ACCCOUNT_LINKING_ERROR,
}
