<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/kc.adoc" as kc>
<#import "/templates/options.adoc" as opts>

<@tmpl.guide
title="Enabling and disabling features"
summary="Understand how to configure Keycloak to use optional features">

Keycloak has packed some functionality in features, some of them not enabled by default. These features include features that are in tech preview or deprecated features. In addition there are some features that are enabled by default, but can be disabled if you don't need them for your specific usage scenario.

=== Enabling and disabling features

Features need to be enabled/disabled using the `build` command.
To enabe a specific feature, for example to enable the ability to use the `token_exchange` functionality, run:

<@kc.build parameters="--features-token_exchange=enabled"/>

To disable it, respectively, run:
<@kc.build parameters="--features-token_exchange=disabled"/>

If you want to have all preview features enabled at once, you can build the server using
<@kc.build parameters="--features=preview"/>

== List of features

|===
|Name|Description|Enabled by default|Support level|Key|CLI|Env
<#list ctx.features.all as feature>

|${feature.name}
|${feature.description}
|${feature.enabledByDefault?string('Yes', 'No')}
|${feature.supportLevel}
|${feature.option.key}
|${feature.option.keyCli}
|${feature.option.keyEnv}
</#list>

|===

</@tmpl.guide>