name: Setup Java
description: Sets up Java.

inputs:
  distribution:
    description: Java distribution.
    required: false
    default: temurin
  java-version:
    description: The Java version that is going to be set up.
    required: false
    default: "25"

runs:
  using: composite
  steps:
    - id: setup-java
      name: Setup Java
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
