name: Setup Java
description: Sets up Java.

inputs:
  distribution:
    description: Java distribution.
    required: false
    default: temurin
  java-version:
    description: The Java version that is going to be set up.
    required: false
    default: "25"

runs:
  using: composite
  steps:
    - id: setup-java
      name: Setup Java
      uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
