name: Setup Java
description: Sets up Java.

inputs:
  distribution:
    description: Java distribution.
    required: false
    default: temurin
  java-version:
    description: The Java version that is going to be set up.
    required: false
    default: "25"

runs:
  using: composite
  steps:
    - id: setup-java
      name: Setup Java
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
