== Domain Mode Example Walkthrough

As noted in the <<domain.adoc#,domain mode>> chapter, {{book.project.name}} comes with a mostly pre-configured clustered domain
setup.  This chapter walks you through this out of the box configuration highlighting each aspect of each configuration
file you need to touch and manage.  At the end, the chapter discusses what changes you'll need to make to this out of the
box configuration to have it work in a real cluster.

The default +profile+ XML block is where you are going to make the bulk of your configuration decisions.  You can edit this file
directly prior to booting the domain controller, but you should use the {{book.appserver.name}} web console or command line interface
to modify it at runtime.

.profile
[source,xml]
----
    <profiles>
        <profile name="default">
           ...
        </profile>
----

The definition of the server group for {{book.project.name}} resides in the +server-groups+ XML block.  It specifies the domain profile
that is used (+default+) and also so default boot arguments for the Java VM when the host controller boots an instance.

.server group
[source,xml]
----
    <server-groups>
        <server-group name="main-server-group" profile="default">
            <jvm name="default">
                <heap size="64m" max-size="512m"/>
            </jvm>
            <socket-binding-group ref="standard-sockets"/>
        </server-group>
    </server-groups>
----
