
[[_saml-jboss-adapter-installation]]
===== Adapter Installation

Each adapter is a separate download on the {project_name} download site.

ifeval::[{project_community}==true]

NOTE: We only test and maintain adapter with the most recent version of WildFly available upon the release. Once new version of
WildFly is released, the current adapters become deprecated and support for them will be removed after next WildFly release.
The other alternative is to switch your applications from WildFly to the JBoss EAP, as the JBoss EAP adapter is supported for much longer period.

Install on WildFly 9 or newer or on JBoss EAP 7:

[source]
----

$ cd $WILDFLY_HOME
$ unzip keycloak-saml-wildfly-adapter-dist.zip
----

Install on JBoss EAP 6.x:
[source]
----

$ cd $JBOSS_HOME
$ unzip keycloak-saml-eap6-adapter-dist.zip
----
endif::[]

ifeval::[{project_product}==true]
Install on JBoss EAP 7.x:
[source]
----

$ cd $EAP_HOME
$ unzip rh-sso-saml-eap7-adapter.zip
----

Install on JBoss EAP 6.x:
[source]
----

$ cd $EAP_HOME
$ unzip rh-sso-saml-eap6-adapter.zip
----
endif::[]


These zip files create new JBoss Modules specific to the WildFly/JBoss EAP SAML Adapter within your WildFly or JBoss EAP distro.

After adding the modules, you must then enable the {project_name} SAML Subsystem within your app server's server configuration: `domain.xml` or `standalone.xml`.

There is a CLI script that will help you modify your server configuration.
Start the server and run the script  from the server's bin directory: 

ifeval::[{project_community}==true]
.WildFly 11 or newer
[source]
----
$ ./bin/jboss-cli.sh --file=adapter-elytron-install-saml.cli
----

.WildFly 10 and older
[source]
----

$ cd $JBOSS_HOME/bin
$ jboss-cli.sh -c --file=adapter-install-saml.cli
----

NOTE: It is possible to use the legacy non-Elytron adapter on WildFly 11 or newer as well, meaning you can use `adapter-install-saml.cli`
even on those versions. However, we recommend to use the newer Elytron adapter.

endif::[]

ifeval::[{project_product}==true]
.JBoss EAP 7.1 or newer
[source]
----
$ ./bin/jboss-cli.sh --file=adapter-elytron-install-saml.cli
----

.JBoss EAP 7.0 and EAP 6
[source]
----

$ cd $JBOSS_HOME/bin
$ jboss-cli.sh -c --file=adapter-install-saml.cli
----

NOTE: It is possible to use the legacy non-Elytron adapter on JBoss EAP 7.1 or newer as well, meaning you can use `adapter-install-saml.cli`
even on those versions. However, we recommend to use the newer Elytron adapter.

endif::[]


The script will add the extension, subsystem, and optional security-domain as described below. 

[source,xml]
----
<server xmlns="urn:jboss:domain:1.4">

    <extensions>
        <extension module="org.keycloak.keycloak-saml-adapter-subsystem"/>
          ...
    </extensions>

    <profile>
        <subsystem xmlns="urn:jboss:domain:keycloak-saml:1.1"/>
         ...
    </profile>
----    

The `keycloak` security domain should be used with EJBs and other components when you need the security context created
in the secured web tier to be propagated to the EJBs (other EE component) you are invoking.
Otherwise this configuration is optional. 

[source,xml]
----

<server xmlns="urn:jboss:domain:1.4">
 <subsystem xmlns="urn:jboss:domain:security:1.2">
    <security-domains>
...
      <security-domain name="keycloak">
         <authentication>
           <login-module code="org.keycloak.adapters.jboss.KeycloakLoginModule"
                         flag="required"/>
          </authentication>
      </security-domain>
    </security-domains>
----

For example, if you have a JAX-RS service that is an EJB within your WEB-INF/classes directory,
you'll want to annotate it with the `@SecurityDomain` annotation as follows:

[source,java]
----

import org.jboss.ejb3.annotation.SecurityDomain;
import org.jboss.resteasy.annotations.cache.NoCache;

import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import java.util.ArrayList;
import java.util.List;

@Path("customers")
@Stateless
@SecurityDomain("keycloak")
public class CustomerService {

    @EJB
    CustomerDB db;

    @GET
    @Produces("application/json")
    @NoCache
    @RolesAllowed("db_user")
    public List<String> getCustomers() {
        return db.getCustomers();
    }
}
----

We hope to improve our integration in the future so that you don't have to specify the
`@SecurityDomain` annotation when you want to propagate a keycloak security context to the EJB tier.

===== JBoss SSO

{appserver_name} has built-in support for single sign-on for web applications deployed to the same {appserver_name}
instance. This should not be enabled when using {project_name}.