// Release notes should contain only headline-worthy new features,
// assuming that people who migrate will read the upgrading guide anyway.

= Asynchronous logging

All available log handlers now support asynchronous logging capabilities.
Asynchronous logging might be useful for deployments requiring high throughput and low latency to move log operations in a separate thread.

For more details, see the https://www.keycloak.org/server/logging[Logging guide].

= Client initiated linking of the user account to identity provider is based on AIA

We added Application initiated action (AIA) implementation for linking a user account to the identity provider. The custom protocol, which was previously
used for client initiated account linking is deprecated now. For more information, see the link:{upgradingguide_link}[{upgradingguide_name}].

= Recovery Codes supported

The Recovery Codes two-factor authentication is promoted from preview to supported feature. For more information about the 2FA method, see the link:{adminguide_link}#_recovery-codes[Recovery Codes] chapter in the {adminguide_name}.
For newly created realms, the browser flow now includes the Recovery Authentication Code Form as _Disabled_, and it can be switched to _Alternative_ by admins if they want to use this feature.

= New AIA action parameter `skip_if_exists` for WebAuthn register

Both WebAuthn Register actions (`webauthn-register` and `webauthn-register-passwordless`) now support a parameter `skip_if_exists` when initiated by the application (AIA). The parameter allows skipping the action if the user already has a credential of that type. For more information, see the link:{adminguide_link}#_webauthn_aia[Registering WebAuthn credentials using AIA] chapter in the {adminguide_name}.

= Experimental support for rolling updates for patch releases

In the previous release, the Keycloak Operator was enhanced to support performing rolling updates of the Keycloak image if both images contain the same version.
This is useful, for example, when switching to an optimized image, changing a theme or a provider source code.

In this release, we extended this to perform rolling update when the new image contains a future patch release from the same `major.minor` release stream as an experimental feature.
Read more in https://www.keycloak.org/server/update-compatibility#rolling-updates-for-patch-releases[Update Compatibility Tool]

= Brokering a OAuth v2 compliant authorization server

A new broker is available to integrate with any OAuth2 compliant Authorization Server. For more information, see the link:{adminguide_link}#_identity_broker_oauth[OAuth v2 identity providers] chapter in the {adminguide_name}.

= Trusting email verification when brokering OpenID Connect Providers

The OpenID Connect broker was updated to trust email verification from OpenID Providers based on the `email_verified` claim when
the `Trust email` setting is enabled. If this claim is set to `true`, the federated user account will have their email marked as verified depending on the value from this claim. The same is true in case the OpenID Provider returns the `email_verified` claim set to `false`, in this case the federated
user account will have their email marked as unverified.

The `email_verified` claim is a standard claim as defined by the https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims[OpenID Connect Core Specification].

