// Release notes should contain only headline-worthy new features,
// assuming that people who migrate will read the upgrading guide anyway.

= Asynchronous logging for higher throughput and lower latency

All available log handlers now support asynchronous logging capabilities.
Asynchronous logging helps deployments that require high throughput and low latency.

For more details on this opt-in feature, see the https://www.keycloak.org/server/logging[Logging guide].

= Simplified linking of the user account to an identity provider

Client initiated Linking a user account to the identity provider is now based on Application initiated action (AIA) implementation.
This aligns configuring this functionality and simplifies the error handling the calling client application,
making it more useful for a broader audience.

The custom protocol, which was previously used for client initiated account linking, is now deprecated.

= Recovering your account if you lose your 2FA credentials

When using for example a one-time-password (OTP) generators as a second factor for authenticating users (2FA), a user can get locked out of their account when they, for example, lose their phone that contains the OTP generator.
To prepare for such a case, the recovery codes feature allows users to print a set of recovery codes as an additional second factor.
If the recovery codes are then allowed as an alternative 2FA in the login flow, they can be used instead of the OTP generated passwords.

With this release, the recovery codes feature is promoted from preview to a supported feature.
For newly created realms, the browser flow now includes the Recovery Authentication Code Form as _Disabled_, and it can be switched to _Alternative_ by admins if they want to use this feature.

For more information about this 2FA method, see the link:{adminguide_link}#_recovery-codes[Recovery Codes] chapter in the {adminguide_name}.

= Simplified registration for WebAuthn and Passkeys

Both WebAuthn Register actions (`webauthn-register` and `webauthn-register-passwordless`) which are also used for Passkeys now support a parameter `skip_if_exists` when initiated by the application (AIA).

This should make it more convenient to use the AIA in scenarios where a user has already set up WebAuthn or Passkeys.
The parameter allows skipping the action if the user already has a credential of that type.

For more information, see the link:{adminguide_link}#_webauthn_aia[Registering WebAuthn credentials using AIA] chapter in the {adminguide_name}.

= Rolling updates for patch releases for minimized downtime (experimental)

In the previous release, the Keycloak Operator was enhanced to support performing rolling updates of the Keycloak image if both images contain the same version.
This is useful, for example, when switching to an optimized image, changing a theme or a provider source code.

In this release, we extended this to perform rolling update when the new image contains a future patch release from the same `major.minor` release stream as an experimental feature.
This can then reduce the downtime of an installation even further as downtime is then only needed when upgrading from one minor release to another.

Read more on how to enable this feature in https://www.keycloak.org/server/update-compatibility#rolling-updates-for-patch-releases[update compatibility command].

= Brokering a OAuth v2 compliant authorization server

A new broker is available to integrate with any OAuth2 compliant Authorization Server. For more information, see the link:{adminguide_link}#_identity_broker_oauth[OAuth v2 identity providers] chapter in the {adminguide_name}.

= Trusting email verification when brokering OpenID Connect Providers

The OpenID Connect broker was updated to trust email verification from OpenID Providers based on the `email_verified` claim when
the `Trust email` setting is enabled. If this claim is set to `true`, the federated user account will have their email marked as verified depending on the value from this claim. The same is true in case the OpenID Provider returns the `email_verified` claim set to `false`, in this case the federated
user account will have their email marked as unverified.

The `email_verified` claim is a standard claim as defined by the https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims[OpenID Connect Core Specification].

