// Release notes should contain only headline-worthy new features,
// assuming that people who migrate will read the upgrading guide anyway.

Read on to learn more about each new feature, and https://www.keycloak.org/docs/latest/upgrading/index.html[find additional details in the upgrading guide] if you are upgrading from a previous release of {project_name}.

= Supported Update Email Workflow

The Update Email Workflow is now a supported feature. The feature provides a more secure and consistent flow to update user emails
because they will be forced to re-authenticate as well as verify their emails before any update to their account.

For more information, see the link:{adminguide_link}#_update-email-workflow[Update Email Workflow] chapter in the {adminguide_name}.

= Option to force management interface to use HTTP.

There's a new option `http-management-scheme` that may be set to `http` to force the management interface to use HTTP rather than inheriting the HTTPS settings of the main interface.

= Additional context information for log messages (preview)

You can now add context information to each log message like the realm or the client that initiated the request.
This helps you to track down a warning or error message in the log to a specific caller or environment

For more details on this opt-in feature, see the https://www.keycloak.org/server/logging[Logging guide].

= Ability to specify a `tlsSecret` on the Keycloak CR `ingress` spec

In order to support basic TLS termination (edge) deployments via the operator, you may now set the Keycloak CR `spec.ingress.tlsSecret` field to a TLS Secret name in the namespace.

= HTTP Access logging

{project_name} supports HTTP access logging to record details of incoming HTTP requests.
While access logs are often used for debugging and traffic analysis, they are also important for security auditing and compliance monitoring.

For more information, see the https://www.keycloak.org/server/logging[Logging guide].
