= Management Interface

To change the port of the management interface, use the first-class citizen field `httpManagement.port` in the Keycloak CR.
To change the properties of the management interface, you can do it by providing `additionalOptions` field.

You can specify the `port` and the `additionalOptions` as follows:

[source,yaml]
----
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  httpManagement:
    port: 9001
  additionalOptions:
    - name: http-management-relative-path
      value: /management
----

NOTE: If you are using a custom image, the Operator is *unaware* of any configuration options that might've been specified there.
For instance, the management interface may use `https`, but the Operator accesses it via `http` when the TLS settings are specified in the custom image.
To ensure proper TLS configuration, use the `tlsSecret` and `truststores` fields in the Keycloak CR so that the Operator can reflect that.

For more details, see <@links.server id="management-interface" />.

