
==== StackOverflow

To enable login with StackOverflow you first have to register an OAuth application on https://stackapps.com/[StackApps].
Then you need to copy the client id, secret and key into the Keycloak Admin Console.

Let's see first how to create an application with StackOverflow.

. Go to http://stackapps.com/apps/oauth/register[registering your application on Stack Apps] url and login here.
  Use any value for `Application Name`, `Application Website` and `Description` you want.
  Set `OAuth Domain` to the domain where your Keycloak instance runs.
  Click the `Register Your Application` button.
. Copy `Client Id`, `Client Secret` and `Key` from the shown page.

Now that you have the client id, secret and key, you can proceed with the creation of a StackOverflow Identity Provider in Keycloak.
As follows:

. Select the `StackOverflow` identity provider from the drop-down box on the top right corner of the identity providers table in Keycloak's Admin Console.
  You should be presented with a specific page to configure the selected provided.
. Copy the client id, client secret and key to their corresponding fields in the Keycloak Admin Console.
  Click `Save`.

That is it! This pretty much what you need to do in order to setup this identity provider.

The table below lists some additional configuration options you may use when configuring this provider.

.Configuration Options
[cols="1,1", options="header"]
|===
|
                                Configuration

|
                                Description

|
                                Default Scopes

|
                                Allows you to manually specify the scopes that users must authorize when authenticating with this provider.
                                For a complete list of scopes, please take a look at application configuration in StackExchange API Authentication documentation. Keycloak uses the empty scope by default.

|===

