
=== Securing Cluster Communication

When cluster nodes are isolated on a private network it requires access to the private network to be able to join a cluster or to view communication in the cluster. In addition you can also enable authentication and encryption for cluster communication. As long as your private network is secure it is not necessary to enable authentication and encryption. {project_name} does not send very sensitive information on the cluster in either case.

ifeval::[{project_product}==true]
If you want to enable authentication and encryption for clustering communication, see link:https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/{appserver_version}/html-single/configuration_guide/configuring_high_availability#securing_cluster[Securing a Cluster] in the _{appserver_name} Configuration Guide_.
endif::[]

ifeval::[{project_community}==true]
If you want to enable authentication and encryption for clustering communication, see the 'High Availability Guide' in the link:{appserver_doc_base_url}/High_Availability_Guide.html[WildFly documentation]. 
endif::[]

