<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/kc.adoc" as kc>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="hostname:v2 - configuring hostname the new way"
summary="Learn how to configure the frontend and backchannel endpoints exposed by {project_name}."
includedOptions="hostname hostname-* proxy">

== The importance of setting up the hostname option

By default, Keycloak mandates the configuration of the `--hostname` option and does not dynamically resolve URLs. This is a security measure.

Keycloak freely discloses its own URLs, for instance, through the OIDC Discovery endpoint, or as part of the password reset link in an email. If the hostname was dynamically interpreted from a hostname header, it could provide a potential attacker with an opportunity to manipulate a URL in the email, redirect a user to the attacker's fake domain, and steal sensitive data such as action tokens, passwords, etc.

By explicitly setting the `--hostname`, we avoid a situation where tokens could be issued by a fraudulent issuer. In this context, the Keycloak server can be initiated using the following command:

[source,bash]
----
kc.sh start --hostname my.keycloak.org
----

== Defining specific parts of the hostname option

As demonstrated in the previous example, the scheme and port are not explicitly defined. In such cases, Keycloak automatically handles these aspects. For instance, the server would be accessible at https://my.keycloak.org:8443[https://my.keycloak.org:8443] based on the given example. However, a reverse proxy will typically expose Keycloak at the default ports, e.g. `443`. In that case it’s desirable to specify the full URL in the `--hostname` option rather than keeping the parts of the URL dynamic. The Keycloak server can then be started as:

[source,bash]
----
kc.sh start --hostname https://my.keycloak.org
----

Similarly, your reverse proxy might expose Keycloak at a different context path. It is possible to configure Keycloak to reflect that via the `--hostname` and `--hostname-admin` options. See the following example:

[source,bash]
----
kc.sh start --hostname https://my.keycloak.org:123/auth
----

== Utilizing Internal URL for communication among clients

Keycloak has the capability to offer a separate URL for backchannel requests, enabling internal communication while maintaining the use of a public URL for frontchannel requests. Moreover, the backchannel is dynamically resolved based on incoming headers. Consider the following example:

[source,bash]
----
kc.sh start --hostname https://my.keycloak.org --hostname-backchannel-dynamic true
----

In this manner, your applications, referred to as clients in Keycloak, can connect with Keycloak through your local network, while Keycloak itself remains publicly accessible at https://my.keycloak.org[https://my.keycloak.org].

== Using edge TLS termination

As you can observe, the HTTPS protocol is the default choice, adhering to Keycloak's commitment to security best practices. However, Keycloak also provides the flexibility for users to opt for HTTP if necessary. This can be achieved simply by specifying the HTTP listener, consult the https://www.keycloak.org/server/enabletls[TLS guide] for details. Assume you have your TLS-termination proxy operational. You can initiate the server as follows:

[source,bash]
----
kc.sh start --hostname https://my.keycloak.org --http-enabled true
----

The result of this configuration is that you can continue to access Keycloak at https://my.keycloak.org[https://my.keycloak.org] via HTTPS, while the proxy interacts with the same Keycloak instance using HTTP and port `8080`.

== Relying on a trusted proxy for the dynamic hostname resolution

If you fully trust your proxy, which correctly sets the Forwarded header, and you don't want to hardcode the hostname, Keycloak can accommodate this. You simply need to initiate the server as follows:

[source,bash]
----
kc.sh start --hostname-strict false --proxy-headers forwarded
----

With this configuration, the server respects the value set by the Forwarded header. This also implies that all endpoints are dynamically resolved.

The `--proxy-headers` option can be also used to resolve the URL partially dynamically when `--hostname` option is not specified as a full URL. For example:

[source,bash]
----
kc.sh start --hostname my.keycloak.org --proxy-headers forwarded
----

In this case, scheme, port and context path are resolved dynamically from X-Forwarded-* headers, while hostname is statically defined as my.keycloak.org[my.keycloak.org].

== Exposing the Administration Console on a separate hostname

If you wish to expose the Admin Console on a different host, you can do so with the following command:

[source,bash]
----
kc.sh start --hostname https://my.keycloak.org --hostname-admin https://admin.my.keycloak.org:8443
----

This allows you to access Keycloak at https://my.keycloak.org[https://my.keycloak.org] and the Keycloak Admin Console at https://admin.my.keycloak.org:8443[https://admin.my.keycloak.org:8443], while the backend continues to use https://my.keycloak.org[https://my.keycloak.org].


NOTE: Keep in mind that none of the options that affect hostname or proxy settings are changing the ports on which the server actually is listening on (it changes only the ports of static resources like JavaScript and CSS links, OIDC well-known endpoints, redirect URIs, etc.). Therefore, you need to use https://www.keycloak.org/server/enabletls[HTTP configuration] options to change the Keycloak server to internally listen on a different port.

== Background - server endpoints

Keycloak exposes several endpoints, each with a different purpose. They are typically used for communication among applications or for managing the Keycloak server itself. We recognize 3 main endpoint groups:

* Frontend
* Backend
* Administration

If you want to work with either of these endpoints, you need to set the base URL. The base URL consists of a several parts:

* a scheme (e.g. https protocol)
* a hostname (e.g. example.keycloak.org)
* a port (e.g. 8443)
* a path (e.g. /auth)

The base URL for each group has an important impact on how tokens are issued and validated, on how links are created for actions that require the user to be redirected to Keycloak (for example, when resetting password through email links), and, most importantly, how applications will discover these endpoints when fetching the OpenID Connect Discovery Document from `realms/{realm-name}/.well-known/openid-configuration`.

=== Frontend

Users and applications use the frontend URL to access Keycloak through a front channel. The front channel is a communication channel, which is publicly accessible. For example browser-based flows (accessing the login page, clicking on the link to reset a password or binding the tokens).

=== Backend

The backend endpoints are those accessible through a public domain or through a private network. They're related to direct backend communication between Keycloak and a client (an application secured by Keycloak). Such communication might be over a local network, avoiding a reverse proxy. Examples of the endpoints that belong to this group are authorization endpoint, token and token introspection endpoint, userinfo endpoint, JWKS URI endpoint, etc.


=== Administration

Similarly to the base frontend URL, you can also set the base URL for resources and endpoints available through the management interface such as the administration console. The server exposes the administration console and static resources using a specific URL. This URL is used for redirect URLs, loading resources (CSS, JS), etc.

== Sources for resolving the URL

As indicated in the previous sections, URLs can be resolved in several ways: they can be dynamically generated, hardcoded, or a combination of both:

* Dynamic from an incoming request:
** Host header, scheme, server port, context path
** Proxy-set headers: `Forwarded` and `X-Forwarded-*`
* Hardcoded:
** Server-wide config (e.g `--hostname`, `--hostname-admin`, etc.)
** Realm configuration for frontend URL

== Validations

* `--hostname` URL and `--hostname-admin` URL are verified that full URL is used, incl. scheme and hostname. Port is validated only if present, otherwise default port for given protocol is assumed (80 or 443).
* In production profile (`kc.sh|bat start`), either `--hostname` or `--hostname-strict` false must be explicitly configured.
** This does not apply for dev profile (`kc.sh|bat start-dev`) where `--hostname-strict false` is the default value.
* If `--hostname` is not configured:
** `--hostname-backchannel-dynamic` must be set to false.
** `--hostname-strict` must be set to false.
* If `--hostname` is configured, --hostname-strict must be set to true.
* If `--hostname-admin` is configured, `--hostname` must be set to a URL (not just hostname).
* If `--hostname-backchannel-dynamic` is set to true, `--hostname` must be set to a URL (not just hostname).

== Troubleshooting

To troubleshoot the hostname configuration, you can use a dedicated debug tool which can be enabled as:

.{project_name} configuration:
<@kc.start parameters="--hostname=mykeycloak --hostname-debug=true"/>

Then after {project_name} started properly, open your browser and go to:

`http://mykeycloak:8080/realms/<your-realm>/hostname-debug`

.By default, this endpoint is disabled (`--hostname-debug=false`)

</@tmpl.guide>
