<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/kc.adoc" as kc>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="Configuring the hostname"
summary="Learn how to configure the frontend and backchannel endpoints exposed by Keycloak."
includedOptions="hostname hostname-* proxy">

== Server Endpoints

Keycloak exposes different endpoints to talk with applications as well as to allow accessing the administration console. These endpoints
can be categorized into three main groups:

* Frontend
* Backend
* Administration Console

The base URL for each group has an important impact on how tokens are issued and validated, on how links are created for actions that require the user
to be redirected to Keycloak (for example, when resetting password through email links), and, most importantly, how applications will
discover these endpoints when fetching the OpenID Connect Discovery Document from `realms/++{realm-name}++/.well-known/openid-configuration`.

=== Frontend

The frontend endpoints are those accessible through a public domain and usually related to authentication/authorization flows that happen
through the front-channel. For instance, when an SPA wants to authenticate their users it redirects them to the `authorization_endpoint` so that users
can authenticate using their browsers through the front-channel.

By default, when the hostname settings are not set, the base URL for these endpoints is based on the incoming request so that the HTTP scheme,
host, port, and path, are the same from the request. The default behavior also has a direct impact on how the server is going to issue tokens given that the issuer is also based on
the URL set to the frontend endpoints. If the hostname settings are not set, the token issuer will also be based on the incoming request and also lack consistency if the client is requesting tokens using different URLs.

When deploying to production you usually want a consistent URL for the frontend endpoints and the token issuer regardless of how the request is constructed.
In order to achieve this consistency, you can set either the `hostname` or the `hostname-url` options.

Most of the time, it should be enough to set the `hostname` option in order to change only the *host* of the frontend URLs:

<@kc.start parameters="--hostname=<host>"/>

When using the `hostname` option the server is going to resolve the HTTP scheme, port, and path, automatically so that:

* `https` scheme is used unless you set `hostname-strict-https=false`
* Use the standard HTTP ports (e.g.: `80` and `443`) if a `proxy` is set or use the port you set to the `hostname-port` option

However, if you want to set not only the host but also a scheme, port, and path, you can set the `hostname-url` option:

<@kc.start parameters="--hostname-url=<scheme>://<host>:<port>/<path>"/>

This option gives you more flexibility as you can set the different parts of the URL from a single option. Note that
the `hostname` and `hostname-url` are mutually exclusive.

=== Backend

The backend endpoints are those accessible through a public domain or through a private network. They are used for a direct communication
between the server and clients without any intermediary but plain HTTP requests. For instance, after the user is authenticated an SPA
wants to exchange the `code` sent by the server with a set of tokens by sending a token request to `token_endpoint`.

By default, the URLs for backend endpoints are also based on the incoming request. To override this behavior, set the `hostname-strict-backchannel` configuration option by entering this command:

<@kc.start parameters="--hostname=<value> --hostname-strict-backchannel=true"/>

By setting the `hostname-strict-backchannel` option, the URLs for the backend endpoints are going to be exactly the same as the frontend endpoints.

When all applications connected to Keycloak communicate through the public URL, set `hostname-strict-backchannel` to `true`.
Otherwise, leave this parameter as `false` to allow client-server communication through a private network.

=== Administration Console

The server exposes the administration console and static resources using a specific URL.

By default, the URLs for the administration console are also based on the incoming request. However, you can set a specific host or base URL if you want
to restrict access to the administration console using a specific URL. Similarly to how you set the frontend URLs, you can use the `hostname-admin` and `hostname-admin-url` options to achieve that.

Most of the time, it should be enough to set the `hostname-admin` option in order to change only the *host* of the administration console URLs:

<@kc.start parameters="--hostname-admin=<host>"/>

However, if you want to set not only the host but also a scheme, port, and path, you can set the `hostname-admin-url` option:

<@kc.start parameters="--hostname-admin-url=<scheme>://<host>:<port>/<path>"/>

Note that the `hostname-admin` and `hostname-admin-url` are mutually exclusive.

To reduce attack surface, the administration endpoints for Keycloak and the Admin Console should not be publicly accessible.
Therefore, you can secure them by using a reverse proxy.
For more information about which paths to expose using a reverse proxy, see <@links.server id="reverseproxy"/>.

== Configuration Examples by Different Scenarios

Through this set of hostname configuration options, Keycloak aims to provide a flexible way to adapt to the characteristics of different environments.

Misconfiguration of the `hostname` and/or its `reverse proxy` options can lead to unusual and unpleasant behavior, such as Keycloak's `Admin Console` not loading correctly.

In an attempt to further improve the user experience and minimize the occurrence of misconfigurations, see the list of sample `hostname` and `proxy` configurations below, which is oriented to possible scenarios that may exist in different computing environments.

The following are more example scenarios and the corresponding commands for setting up the `hostname` and/or `proxy` options.

> Note that the `start` command requires setting up TLS. The corresponding options are not shown for example purposes. For more details, see <@links.server id="enabletls"/>.

=== Scenario 01 - Development test in localhost over HTTP

.Description:
The most basic option to run in `localhost` with all default values. For development and/or local testing purposes.

.Keycloak configuration:

  <@kc.startdev parameters=""/>

All 3 endpoint categories are available at: `http://localhost:8080`

---

=== Scenario 02 - Exposing the server with custom hostname over HTTP

.Description:
Just setting a custom `hostname` to be reachable via HTTP only.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --http-enabled=true --hostname-strict-https=false"/>

All 3 endpoint categories are available at: `http://mykeycloak.com:8080`

---

=== Scenario 03 - Exposing the server with custom hostname over HTTPS

.Description:
Setting a custom `hostname` to be reachable over HTTPS and exposing the server without a proxy.

.Keycloak configuration:
Set the HTTPS/TLS Certificates in Keycloak. For more details, see <@links.server id="enabletls"/>.

  <@kc.start parameters="-hostname=mykeycloak.com --https-certificate-file=/path-to-file/the-cert.pem --https-certificate-key-file=/path-to-file/the-cert-key.pem"/>

All 3 endpoint categories are available at: `https://mykeycloak.com:8443`

---

=== Scenario 04 - Exposing the server with custom hostname and Admin Console URL and both over HTTP

.Description:
Setting a custom `hostname` for Frontend and Backend, and setting a different URL to reach Admin Console UI. Both reachable via HTTP only.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --hostname-admin=admin.mykeycloak.com --http-enabled=true --hostname-strict-https=false"/>

Frontend/Backend available at: `http://mykeycloak.com:8080`

Admin Console available at: `http://admin.mykeycloak.com:8080`

---

=== Scenario 05 - Exposing the server with custom hostname and Admin Console URL and both over HTTPS

.Description:
Setting a custom `hostname` for Frontend/Backend endpoints, and setting a different URL to reach `Admin Console UI`. Both reachable over HTTPS.

.Keycloak configuration:

Set the HTTPS/TLS Certificates in Keycloak. For more details, see <@links.server id="enabletls"/>.

  <@kc.start parameters="--hostname=mykeycloak.com --hostname-admin=admin.mykeycloak.com --https-certificate-file=/path-to-file/the-cert.pem --https-certificate-key-file=/path-to-file/the-cert-key.pem"/>

Frontend/Backend available at: `https://mykeycloak.com:8443`

Admin Console available at: `https://admin.mykeycloak.com:8443`

---

=== Scenario 06 - Exposing the server with custom hostname over HTTP and behind a proxy in 'edge' mode

.Description:
Setting a custom `hostname` and setting a `reverse proxy` in 'edge' mode in front of Keycloak, which redirects the incoming requests on its port [80] to Keycloak on port [8080], via HTTP in both ends.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --proxy=edge --http-enabled=true --hostname-strict-https=false"/>

For more information about which paths to expose using a reverse proxy, see <@links.server id="reverseproxy"/>.

All 3 endpoint categories are available at: `http://mykeycloak.com`

---

=== Scenario 07 - Exposing the server with custom hostname over HTTPS and behind a proxy in 'edge' mode

.Description:
Setting a custom `hostname` and setting a `reverse proxy` in 'edge' mode in front of Keycloak, which redirects the incoming requests on its port [443] to Keycloak on port [8080], over HTTPS only in `proxy` end.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --proxy=edge"/>

Set the HTTPS/TLS termination on your `reverse proxy` end. In this scenario, Keycloak remains in HTTP only, and trust in your `proxy`.

All 3 endpoint categories are available at: `https://mykeycloak.com`

---

=== Scenario 08 - Exposing the server with custom hostname over HTTP and behind a proxy in 'passthrough' mode

.Description:
Setting a custom `hostname` and setting a `reverse proxy` in 'passthrough' mode in front of Keycloak, which redirects the incoming requests on its port [80] to Keycloak on port [8080], via HTTP only in both ends.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --proxy=passthrough --http-enabled=true --hostname-strict-https=false"/>

Reverse proxy doesn't have HTTPS/TLS termination and trust in Keycloak. The access to your Keycloak instance behind the proxy is then provided over HTTP only, ## which is not recommended ##.

All 3 endpoint categories are available at: `http://mykeycloak.com`

---

=== Scenario 09 - Exposing the server with custom hostname over HTTPS and behind a proxy in 'passthrough' mode

.Description:
Setting a custom `hostname` and setting a `reverse proxy` in 'passthrough' mode in front of Keycloak, which redirects the incoming requests on its port [80] to Keycloak on port [8080], via HTTP only in both ends.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --proxy=passthrough --https-certificate-file=/path-to-file/the-cert.pem --https-certificate-key-file=/path-to-file/the-cert-key.pem"/>

Your `reverse proxy` don't have HTTPS/TLS termination and trust in Keycloak, which has HTTP/TLS termination. Set the HTTPS/TLS certificates in Keycloak. For more details, see <@links.server id="enabletls"/>;

For more information about which paths to expose using a `reverse proxy`, see <@links.server id="reverseproxy"/>.

All 3 endpoint categories are available at: `https://mykeycloak.com`

---

=== Scenario 10 - Exposing the server with custom hostname over HTTPS and behind a proxy in 'reencrypt' mode

.Description:
Setting a custom `hostname` and setting a `reverse proxy` in 'reencrypt' mode in front of Keycloak, which redirects the incoming requests on its port [443] to Keycloak on port [8443], via HTTPS on both ends.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --proxy=reencrypt --https-certificate-file=/path-to-file/the-cert.pem --https-certificate-key-file=/path-to-file/the-cert-key.pem"/>

Either your `reverse proxy` and Keycloak have HTTPS/TLS termination, with different certificates. Set the properly HTTPS/TLS certificates in Keycloak. For more details, see <@links.server id="enabletls"/>.

Also set the HTTPS/TLS termination on your `reverse proxy`. For more information about which paths to expose using a `reverse proxy`, see <@links.server id="reverseproxy"/>.

All 3 endpoint categories are available at: `https://mykeycloak.com`

---

=== Scenario 11 - Exposing the server with custom hostname and Admin Console URL over HTTP and behind a proxy in 'edge' mode

.Description:
Keycloak is behind a `reverse proxy` in 'edge' mode. Setting a custom `hostname` for Frontend and Backend, and setting a different URL to reach `Admin Console UI`. Both reachable via HTTP only.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --hostname-admin=admin.mykeycloak.com --proxy=edge --http-enabled=true --hostname-strict-https=false"/>

For more information about which paths to expose using a `reverse proxy`, see <@links.server id="reverseproxy"/>.

No HTTS/TLS termination in any end, ## which is not recommended. ##

Frontend/Backend available at: `http://mykeycloak.com`

Admin Console available at: `http://admin.mykeycloak.com`

---

=== Scenario 12 - Exposing the server with custom hostname and Admin Console URL over HTTPS and behind a proxy in 'edge' mode

.Description:
Keycloak is behind a `reverse proxy` in 'edge' mode. Setting a custom `hostname for Frontend and Backend, and setting a different URL to reach Admin Console UI. `Reverse proxy` in 'edge' mode in front of Keycloak, which redirects the incoming requests on its port [443] to Keycloak on port [8080], via HTTPS only in `proxy` end.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --hostname-admin=admin.mykeycloak.com --proxy=edge"/>

For more information about which paths to expose using a `reverse proxy`, see <@links.server id="reverseproxy"/>.

You must set the HTTS/TLS termination in `reverse proxy` end. Keycloak accept HTTP and trusts on `reverse proxy HTTPS/TLS termination settings.

Frontend/Backend available at: `https://mykeycloak.com`

Admin Console available at: `https://admin.mykeycloak.com`

---

=== Scenario 13 - Exposing the server with custom hostname and Admin Console URL over HTTP and behind a Proxy in 'passthrough' mode

.Description:
Keycloak is behind a `reverse proxy` in 'passthrough' mode. Setting a custom `hostname for Frontend and Backend, and setting a different URL to reach `Admin Console UI`. Both reachable via HTTP only.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --hostname-admin=admin.mykeycloak.com --proxy=passthrough --http-enabled=true --hostname-strict-https=false"/>

For more information about which paths to expose using a `reverse proxy`, see <@links.server id="reverseproxy"/>.

No HTTS/TLS termination in any end, ## which is not recommended ##.

Frontend/Backend available at: `http://mykeycloak.com`

Admin Console available at: `http://admin.mykeycloak.com`

---

=== Scenario 14 - Exposing the server with custom hostname and Admin Console URL over HTTPS and behind a proxy in 'passthrough' mode

.Description:
Keycloak is behind a `reverse proxy` in 'passthrough' mode. Setting a custom `hostname` for Frontend/Backend, and setting a different URL to reach `Admin Console UI`. `Reverse proxy` in 'passthrough' mode in front of Keycloak, which redirects the incoming requests on its port [80] to Keycloak on port [8443], via HTTPS only in Keycloak end.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak.com --hostname-admin=admin.mykeycloak.com --proxy=passthrough --https-certificate-file=/path-to-file/the-cert.pem --https-certificate-key-file=/path-to-file/the-cert-key.pem"/>

For more information about which paths to expose using a `reverse proxy`, see <@links.server id="reverseproxy"/>.

Set the HTTPS/TLS certificates in Keycloak. For more details, see <@links.server id="enabletls"/>.

Frontend/Backend available at: `https://mykeycloak.com`

Admin Console available at: `https://admin.mykeycloak.com`

---

=== Scenario 15 - Exposing the server with custom hostname and Admin Console URL over HTTPS and behind a proxy in 'reencrypt' mode

.Description:
Keycloak is behind a `reverse proxy` in 'reencrypt' mode. Setting a custom `hostname` for Frontend/Backend endpoints, and setting a different URL to reach `Admin Console UI`. `Reverse proxy` in 'reencrypt' mode in front of Keycloak, which redirects the incoming requests on its port [443] to Keycloak on port [8443], via HTTPS in both ends.

.Keycloak configuration:

  <@kc.start parameters="--hostname-admin=admin.mykeycloak.com --proxy=reencrypt --https-certificate-file=/path-to-file/the-cert.pem --https-certificate-key-file=/path-to-file/the-cert-key.pem"/>

Either your `reverse proxy` and Keycloak have HTTPS/TLS termination, with different certificates. Set the properly HTTPS/TLS certificates in Keycloak. For more details, see <@links.server id="enabletls"/>;

Also set the HTTPS/TLS termination on your `reverse proxy`. For more information about which paths to expose using a `reverse proxy`, see <@links.server id="reverseproxy"/>.

Frontend/Backend available at: `https://mykeycloak.com`

Admin Console available at: `https://admin.mykeycloak.com`

---

=== [WIP - To be checked] Scenario 16 - Forcing backend endpoints to use the same URL the server is exposed

.Description:
In this example, backend endpoints are exposed using the same URL used by the server so that clients always fetch the same URL
regardless of the origin of the request.

.Keycloak configuration:

  <@kc.start parameters="--hostname=mykeycloak --hostname-strict-backchannel=true"/>

All 3 endpoint categories are available at: `[TBD]`

---

=== [WIP - To be checked] Scenario 17 - Exposing the server using a port other than the default ports

.Description:
In this example, the server is accessible using a port other than the default ports.

.Keycloak configuration:

  <@kc.start parameters="--hostname-url=https://mykeycloak:8989"/>

All 3 endpoint categories are available at: `[TBD]`

== Troubleshooting

To troubleshoot the hostname configuration, you can use a dedicated debug tool which can be enabled as:

.Keycloak configuration:
<@kc.start parameters="--hostname=mykeycloak --hostname-debug=true"/>

Then after Keycloak started properly, open your browser and go to:

`http://mykeycloak:8080/realms/<your-realm>/hostname-debug`

.By default, this endpoint is disabled (`--hostname-debug=false`)


</@tmpl.guide>
