name: Aurora Delete

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the Aurora DB cluster'
        type: string
        required: true
      region:
        description: 'The AWS region used to host the Aurora DB'
        type: string
        required: true

permissions:
  contents: read

jobs:
  delete:
    name: Delete Aurora DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Initialize AWS client
        run: |
          aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
          aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
          aws configure set region ${{ inputs.region }}

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - id: delete
        shell: bash
        run: ./aurora_delete.sh
        working-directory: .github/scripts/aws/rds
        env:
          AURORA_CLUSTER: ${{ inputs.name }}
          AURORA_REGION: ${{ inputs.region }}
