name: Conformance Tests

on:
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"

concurrency:
  group: conformance-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

  conformance-tests:
    name: Conformance Tests
    runs-on: ubuntu-latest
    needs:
      - build
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - id: integration-test-setup
        name: Integration test setup
        uses: ./.github/actions/integration-test-setup

      - name: Build tar keycloak-quarkus-dist
        run: ./mvnw package -pl quarkus/server/,quarkus/dist/

      - name: Run conformance tests
        run: ./mvnw package -f tests/conformance/pom.xml
