name: Warm JS Wireit cache

on:
  push:
    branches:
      - main
    paths:
      - 'js/**'
      - 'services/**'
      - 'rest/admin-ui-ext/**'
      - 'themes/**'
      - '.github/actions/pnpm-setup/**'
      - '.github/workflows/js-wireit-cache.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  warm-wireit-cache:
    name: Warm Wireit cache on main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/pnpm-setup

      - name: Build Keycloak Admin Client
        run: pnpm --fail-if-no-match --filter @keycloak/keycloak-admin-client build
        working-directory: js
