name: Build Keycloak, Create Release and Publish Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  release_and_publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract semver
        id: extract_semver
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          if [[ "$TAG_NAME" =~ ^([0-9]+.[0-9]+.[0-9]+) ]]; then
            echo "SEMVER=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "SEMVER=$TAG_NAME" >> $GITHUB_ENV
          fi

      - name: Set version
        run: ./set-version.sh ${{ env.SEMVER }}

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: quarkus/dist/target/keycloak-*.tar.gz
          tag_name: ${{ env.TAG_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./quarkus/container/
          file: ./quarkus/container/Dockerfile
          push: true
          tags: ghcr.io/vunetsystems/keycloak:${{ env.TAG_NAME }}
          build-args: |
            KEYCLOAK_VERSION=${{ env.TAG_NAME }}
