name: Scan dependencies
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  define-refs:
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak'
    runs-on: ubuntu-latest
    outputs:
      refs: ${{ steps.refs.outputs.refs }}
    steps:
      - id: refs
        run: |
          BRANCHES=($(gh api --cache 1h --paginate /repos/${{ github.repository }}/branches -q '.[] | .name | select(startswith("release"))' | sort -V -r))
          LATEST_REL_BRANCH=$(echo ${BRANCHES[0]} | sed 's|release/||') 
          
          REFS='['
          REFS+="\"refs/heads/main\""
          for BRANCH in "${BRANCHES[@]}"; do
              REFS+=", "
              REFS+="\"refs/heads/$BRANCH\""
          done

          REFS+=']'

          echo "refs=$REFS" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  scan-dependencies:
    name: Scan dependencies
    runs-on: ubuntu-latest
    needs: define-refs
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        ref: ${{ fromJSON(needs.define-refs.outputs.refs) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ matrix.ref }}

      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@81e514348e19b6112ce2a7e3ecbafe19c1e1f567 # v0.3.1
        with:
          cache: true
          version: v0.70.0 # There's an issue in v0.71.0 that makes it not work with Keycloak
      - name: Setup SNYK
        uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Trivy scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivyignores: .trivy/trivyignore.yaml
          format: 'json'
          output: 'trivy-report.json'
          scanners: 'vuln'          
          skip-setup-trivy: true

      - name: SNYK scan
        run: |
          snyk test --policy-path=.github/snyk/.snyk --json-file-output=snyk-report.json quarkus/deployment/ && ecode=$? || ecode=$? 
          if [ "$ecode" -gt 1 ]; then
            exit $ecode
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_PAT }}

      - run: echo "REPORT_NAME=$(echo 'reports-${{ matrix.ref }}' | sed 's|/|_|g')" >> $GITHUB_ENV

      - name: Upload Report to Run
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.REPORT_NAME }}
          path: |
            snyk-report.json
            trivy-report.json
          retention-days: 7

  parse-reports:
    name: Parse Reports
    needs: scan-dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Download report artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: /tmp/reports
          pattern: reports-*
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: List artifacts
        run: tree /tmp/reports
      - name: Parse reports
        run: ./mvnw -f misc/vuln-to-issues package exec:java -Dexec.mainClass=org.keycloak.misc.vulns.Main -Dexec.args="/tmp/reports/"
