name: Stability - Keycloak JavaScript CI

on:
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"
  RETRY_COUNT: 0

defaults:
  run:
    shell: bash

jobs:
  build-keycloak:
    name: Build Keycloak
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Prepare archive for upload
        run: |
          mv ./quarkus/dist/target/keycloak-999.0.0-SNAPSHOT.tar.gz ./keycloak-999.0.0-SNAPSHOT.tar.gz

      - name: Upload Keycloak dist
        uses: actions/upload-artifact@v4
        with:
          name: keycloak
          path: keycloak-999.0.0-SNAPSHOT.tar.gz

  generate-test-seed:
    name: Generate Test Seed
    runs-on: ubuntu-latest
    outputs:
      seed: ${{ steps.generate-random-number.outputs.value }}
    steps:
      - name: Generate random number
        id: generate-random-number
        shell: bash
        run: |
          echo "value=$(shuf -i 1-100 -n 1)" >> $GITHUB_OUTPUT

  admin-ui-e2e:
    name: Admin UI E2E
    needs:
      - build-keycloak
      - generate-test-seed
    runs-on: ubuntu-latest
    env:
      WORKSPACE: keycloak-admin-ui
    strategy:
      matrix:
        browser: [chromium, firefox]
        exclude:
          # Only test with Firefox on scheduled runs
          - browser: ${{ github.event_name != 'workflow_dispatch' && 'firefox' || '' }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/pnpm-setup

      - name: Compile Admin Client
        run: pnpm --fail-if-no-match --filter @keycloak/keycloak-admin-client build
        working-directory: js

      - name: Download Keycloak server
        uses: actions/download-artifact@v4
        with:
          name: keycloak

      - name: Setup Java
        uses: ./.github/actions/java-setup

      - name: Start Keycloak server
        run: |
          tar xfvz keycloak-999.0.0-SNAPSHOT.tar.gz
          keycloak-999.0.0-SNAPSHOT/bin/kc.sh start-dev --features=admin-fine-grained-authz:v2,transient-users &> ~/server.log &
        env:
          KC_BOOTSTRAP_ADMIN_USERNAME: admin
          KC_BOOTSTRAP_ADMIN_PASSWORD: admin
          KC_BOOTSTRAP_ADMIN_CLIENT_ID: temporary-admin-service
          KC_BOOTSTRAP_ADMIN_CLIENT_SECRET: temporary-admin-service

      - name: Install Playwright browsers
        run: pnpm --fail-if-no-match --filter ${{ env.WORKSPACE }} exec playwright install --with-deps
        working-directory: js

      - name: Run Playwright tests
        run: pnpm --fail-if-no-match --filter ${{ env.WORKSPACE }} test:integration --project=${{ matrix.browser }}
        working-directory: js

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: admin-ui-playwright-report-${{ matrix.browser }}
          path: js/apps/admin-ui/playwright-report
          retention-days: 30

      - name: Upload server logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: admin-ui-server-log-${{ matrix.browser }}
          path: ~/server.log

