[id="jboss7_adapter_rpm"]
===== Installing JBoss EAP 7 adapters from an RPM

NOTE: With Red Hat Enterprise Linux 7, the term channel was replaced with the term repository. In these instructions only the term repository is used.

.Prerequisites

You must subscribe to the {appserver_name} {appserver_version} repository before you can install the {appserver_name} 7 adapters from an RPM.

* Ensure that your Red Hat Enterprise Linux system is registered to your account using Red Hat Subscription Manager. For more information see the link:https://access.redhat.com/documentation/en-us/red_hat_subscription_management/2022[Red Hat Subscription Management documentation].

* If you are already subscribed to another JBoss EAP repository, you must unsubscribe from that repository first.
+
For Red Hat Enterprise Linux 6, 7: Using Red Hat Subscription Manager, subscribe to the {appserver_name} {appserver_version} repository using the following command. Replace <RHEL_VERSION> with either 6 or 7 depending on your Red Hat Enterprise Linux version.
+
[source,bash,subs="attributes+"]
----
$ sudo subscription-manager repos --enable=jb-eap-7-for-rhel-<RHEL_VERSION>-server-rpms
----
+
For Red Hat Enterprise Linux 8: Using Red Hat Subscription Manager, subscribe to the {appserver_name} {appserver_version} repository using the following command:
+
[source,bash,subs="attributes+"]
----
$ sudo subscription-manager repos --enable=jb-eap-{appserver_version}-for-rhel-8-x86_64-rpms --enable=rhel-8-for-x86_64-baseos-rpms --enable=rhel-8-for-x86_64-appstream-rpms
----

.Procedure

. Install the {appserver_name} 7 adapters for OIDC based on your version of Red Hat Enterprise Linux.

* Install on Red Hat Enterprise Linux 6, 7:
+
[source,bash,subs="attributes+"]
----
$ sudo yum install eap7-keycloak-adapter-sso7_6
----

* Install on  Red Hat Enterprise Linux 8:
+
[source,bash,subs="attributes+"]
----
$ sudo dnf install eap7-keycloak-adapter-sso7_6
----
+
NOTE: The default EAP_HOME path for the RPM installation is /opt/rh/eap7/root/usr/share/wildfly.

. Run the installation script for the OIDC module.
+
[source,bash,subs="attributes+"]
----
$ $EAP_HOME/bin/jboss-cli.sh -c --file=$EAP_HOME/bin/adapter-install.cli
----

Your installation is complete.

[id="jboss6_adapter_rpm"]
===== Installing JBoss EAP 6 adapters from an RPM

NOTE: With Red Hat Enterprise Linux 7, the term channel was replaced with the term repository. In these instructions only the term repository is used.

You must subscribe to the JBoss EAP 6 repository before you can install the EAP 6 adapters from an RPM.

.Prerequisites

* Ensure that your Red Hat Enterprise Linux system is registered to your account using Red Hat Subscription Manager. For more information see the link:https://access.redhat.com/documentation/en-us/red_hat_subscription_management/2022[Red Hat Subscription Management documentation].

* If you are already subscribed to another JBoss EAP repository, you must unsubscribe from that repository first.
+
Using Red Hat Subscription Manager, subscribe to the JBoss EAP 6 repository using the following command. Replace <RHEL_VERSION> with either 6 or 7 depending on your Red Hat Enterprise Linux version.
+
[source,bash,subs="attributes+"]
----
$ sudo subscription-manager repos --enable=jb-eap-6-for-rhel-<RHEL_VERSION>-server-rpms
----

.Procedure

. Install the EAP 6 adapters for OIDC using the following command:
+
[source,bash,subs="attributes+"]
----
$ sudo yum install keycloak-adapter-sso7_6-eap6
----
+
NOTE: The default EAP_HOME path for the RPM installation is /opt/rh/eap6/root/usr/share/wildfly.

. Run the installation script for the OIDC module.
+
[source,bash,subs="attributes+"]
----
$ $EAP_HOME/bin/jboss-cli.sh -c --file=$EAP_HOME/bin/adapter-install.cli
----

Your installation is complete.
