
[[_master_realm_access_control]]
=== Master realm access control

The `master` realm in {project_name} is a special realm and treated differently than other realms.
Users in the {project_name} `master` realm can be granted permission to manage zero or more realms that are deployed on the {project_name} server.
When a realm is created, {project_name} automatically creates various roles that grant permissions to access that new realm.
Access to The Admin Console and Admin REST endpoints can be controlled by mapping these roles to users in the `master` realm.
It's possible to create multiple superusers,  as well as users that can only manage specific realms.

==== Global roles

There are two realm-level roles in the `master` realm.
These are:

* admin
* create-realm

Users with the `admin` role are superusers and have full access to manage any realm on the server.  Users with the `create-realm` role
are allowed to create new realms.  They will be granted full access to any new realm they create.

IMPORTANT: Admins with the `create-realm` role who do not have the `admin` role will also need the realm-specific `query-realms` role to be able to create and list realms in the Admin Console.

==== Realm specific roles

Admin users within the `master` realm can be granted management privileges to one or more other realms in the system.
Each realm in {project_name} is represented by a client in the `master` realm.
The name of the client is `<realm name>-realm`.  These clients each have client-level roles defined which define varying
level of access to manage an individual realm.

The roles available are:

* **create-client**: Allows creating new clients in the realm.
* **export-realm**: Allows exporting the realm configuration, including clients, groups and roles (but no secrets).
* **impersonation**: Allows impersonating other users for testing and support purposes.
* **manage-authorization**: Allows creating, modifying, and deleting authorization policies and resource-based access controls.
* **manage-clients**: Allows full management of all clients, including creation, configuration, and deletion.
* **manage-events**: Allows configuring event listeners, enabling or disabling event logging, and clearing event logs.
* **manage-identity-providers**: Allows creating, configuring, and deleting identity providers and federation settings.
* **manage-organizations**: Allows creating, configuring, and managing organizations.
* **manage-realm**: Allows full management of realm settings and configuration. Implies `view-realm`.
* **manage-users**: Allows full management of users, including creation, modification, deletion, and role assignment.
* **query-clients**: Allows querying and listing clients without granting view or modification access.
* **query-groups**: Allows querying and listing groups without granting view or modification access.
* **query-organizations**: Allows querying and listing organizations without granting view or modification access.
* **query-realms**: Allows querying and listing available realms.
* **query-users**: Allows querying and listing users without granting view or modification access.
* **view-authorization**: Allows viewing authorization policies and resource configurations.
* **view-clients**: Allows viewing client details and configurations (incl. client secrets) without modification access.
* **view-events**: Allows viewing event logs and event configuration without modification access.
* **view-identity-providers**: Allows viewing identity provider configurations without modification access.
* **view-organizations**: Allows viewing organization configurations without modification access.
* **view-realm**: Allows viewing realm settings and general realm information.
* **view-users**: Allows viewing user details without modification access.

Assign the roles you want to your users and they will only be able to use that specific part of the administration console.

IMPORTANT: Admins with the `manage-users` role will only be able to assign admin roles to users that they themselves have.  So, if an admin has the `manage-users` role but doesn't have the `manage-realm` role, they will not be able to assign this role.



