apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - keycloaks.k8s.keycloak.org-v1.yml
  - keycloakrealmimports.k8s.keycloak.org-v1.yml
  - kubernetes.yml
  
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
    setRoleBindingSubjects: allServiceAccounts
    fieldSpecs:
    - path: metadata/namespace
      create: true
