= WildFly distribution removed

With this release, we are removing the WildFly distribution which was already deprecated for some time. In case you are still using it, see our https://www.keycloak.org/migration/migrating-to-quarkus[Migration Guide] for switching to Quarkus distribution.

With that, we are also removing the legacy Kubernetes Operator and keeping only the new Quarkus-based Operator (see below for its release notes).

= Allow setting a base URL when configuring the hostname

In this release, we are introducing two additional server options to set a base URL for front end and Admin Console URLs.

* `hostname-url`
* `hostname-admin-url`

More details can be found at the https://www.keycloak.org/server/hostname[Configuring the Hostname Guide].

= Improvements to `kc.bat` when running Keycloak on Windows

In this release, we are making important changes to `kc.bat` to give the same experience as when running on Linux.

= Upgrade of embedded H2 database

{project_name} ships for development purposes with an H2 database driver. As it is intended for development purposes only, it should never be used in a production environment.

In this release, the H2 driver has been upgraded from version 1.x to version 2.x.
See link:{upgradingguide_link}[{upgradingguide_name}] for details on how to migrate.

= New Keycloak Operator upgrade

We are happy to announce that the new Quarkus-based Keycloak Operator is no longer a tech preview feature. We added new functionality as well as the quality of life improvements. Some of them resulted in breaking changes.

It’s important to emphasize that none of these breaking changes will come into effect automatically. Please, read our link:{upgradingguide_link}[{upgradingguide_name}] for more information.

== Realm Operator

As the new Operator currently lacks some of the CRs (e.g. Client and User), we're introducing a temporary workaround in the form of Realm Operator. Please see its https://github.com/keycloak/keycloak-realm-operator[GitHub Repository] for more details. See also https://www.keycloak.org/2022/09/operator-crs["The future of Keycloak Operator CRs" blogpost].

= Deprecated methods from data providers and models were removed

Several deprecated methods were removed from data providers and models.
If not done already, their usage needs to be replaced with the corresponding
replacement documented in Javadoc of Keycloak 19 release. See
link:{upgradingguide_link}[{upgradingguide_name}] for more details.
