= Allow setting a base URL when configuring the hostname

In this release, we are introducing two additional server options to set a base URL for front end and Admin Console URLs.

* `hostname-url`
* `hostname-admin-url`

More details can be found at the https://www.keycloak.org/server/hostname[Configuring the Hostname Guide].

= Improvements to `kc.bat` when running Keycloak on Windows

In this release, we are making important changes to `kc.bat` to give the same experience as when running on Linux.

= Upgrade of embedded H2 database

{project_name} ships for development purposes with an H2 database driver. As it is intended for development purposes only, it should never be used in a production environment.

In this release, the H2 driver has been upgraded from version 1.x to version 2.x.
See link:{upgradingguide_link}[{upgradingguide_name}] for details on how to migrate.

= Keycloak Operator upgrade

We are happy to announce that Keycloak Operator is no longer a tech preview feature. We added new functionality as well as the quality of life improvements. Some of them resulted in breaking changes.

It’s important to emphasize that none of these breaking changes will come into effect automatically. Please, read our link:{upgradingguide_link}[{upgradingguide_name}] for more information.
