= Highlights

== WildFly 17 Upgrade

Keycloak server was upgraded to use WildFly 17 under the covers.

== Tomcat 9 adapter support

Java adapter for Apache Tomcat 8 and Apache Tomcat 9 was unified and now it serves for both of them.

== New Account Console

A lot of work has been done on the new Account Console and Account REST API. It's not quite ready yet, but it's getting
there and hopefully will be fully done for Keycloak 8.

== Testing and release automation

The Keycloak team has spent a significant amount of time on automation around testing and releases both for Keycloak and
Red Hat Single Sign-On.

= Other improvements

* PKCE support added to JavaScript adapter. Thanks to https://github.com/thomasdarimont[thomasdarimont]
* Oracle database support added to Keycloak container image. Thanks to https://github.com/nerdstep[nerdstep]
* Clock Skew support added to SAML adapter. Thanks to https://github.com/steevebtib[steevebtib]
* TypeScript support for Node.js adapter. Thanks to https://github.com/evanshortiss[evanshortiss]
* Allow Gatekeeper to provide unencrypted token in header, while encrypting in cookie. Thanks to https://github.com/fredbi[fredbi]
